// deck_sr.js — автогенерация из Excel
// Формат элементов: { id: N, word: "sr", uk: "укр", ru: "рус" }
window.decks = window.decks || {};

// === SR_VERBS ===
window.decks.sr_verbs = [
  { id: 1, word: "kuvati", uk: "готувати", ru: "готовить" },
  { id: 2, word: "pržiti", uk: "смажити", ru: "жарить" },
  { id: 3, word: "peći", uk: "пекти/запікати", ru: "печь" },
  { id: 4, word: "seći", uk: "різати", ru: "резать" },
  { id: 5, word: "oprati", uk: "помити/випрати", ru: "помыть/постирать" },
  { id: 6, word: "čistiti", uk: "чистити/прибирати", ru: "чистить/убирать" },
  { id: 7, word: "otvoriti", uk: "відкрити", ru: "открыть" },
  { id: 8, word: "zatvoriti", uk: "закрити", ru: "закрыть" },
  { id: 9, word: "upaliti", uk: "увімкнути", ru: "включить" },
  { id: 10, word: "ugasiti", uk: "вимкнути/погасити", ru: "выключить/потушить" },
  { id: 11, word: "čekati", uk: "чекати", ru: "ждать" },
  { id: 12, word: "dočekati", uk: "дочекатися/зустріти", ru: "дождаться/встретить" },
  { id: 13, word: "pozvati", uk: "покликати/запросити", ru: "позвать/пригласить" },
  { id: 14, word: "zvati", uk: "кликати/дзвонити", ru: "звать/звонить" },
  { id: 15, word: "telefonirati", uk: "телефонувати", ru: "звонить по телефону" },
  { id: 16, word: "kupovati", uk: "купувати", ru: "покупать" },
  { id: 17, word: "prodavati", uk: "продавати", ru: "продавать" },
  { id: 18, word: "platiti", uk: "заплатити", ru: "заплатить" },
  { id: 19, word: "naručiti", uk: "замовити", ru: "заказать" },
  { id: 20, word: "donositi", uk: "приносити", ru: "приносить" },
  { id: 21, word: "odnositi", uk: "відносити", ru: "относить" },
  { id: 22, word: "voziti", uk: "вести/керувати", ru: "водить" },
  { id: 23, word: "voziti se", uk: "їхати", ru: "ехать" },
  { id: 24, word: "plivati", uk: "плавати", ru: "плавать" },
  { id: 25, word: "leteti", uk: "літати", ru: "летать" },
  { id: 26, word: "voziti bicikl", uk: "їздити на велосипеді", ru: "ездить на велосипеде" },
  { id: 27, word: "jahati", uk: "їздити верхи", ru: "ехать верхом" },
  { id: 28, word: "penjati se", uk: "підійматися", ru: "подниматься" },
  { id: 29, word: "silaziti", uk: "спускатися", ru: "спускаться" },
  { id: 30, word: "ulaziti", uk: "заходити", ru: "входить" },
  { id: 31, word: "izlaziti", uk: "виходити", ru: "выходить" },
  { id: 32, word: "sedati", uk: "сідати", ru: "садиться" },
  { id: 33, word: "ustajati", uk: "вставати", ru: "вставать" },
  { id: 34, word: "padati", uk: "падати", ru: "падать" },
  { id: 35, word: "nositi", uk: "носити", ru: "носить" },
  { id: 36, word: "gurati", uk: "штовхати", ru: "толкать" },
  { id: 37, word: "vući", uk: "тягнути", ru: "тянуть" },
  { id: 38, word: "voziti autobus", uk: "керувати автобусом", ru: "водить автобус" },
  { id: 39, word: "voziti auto", uk: "керувати машиною", ru: "водить машину" },
  { id: 40, word: "parkirati", uk: "паркувати", ru: "парковать" },
  { id: 41, word: "pitati", uk: "питати", ru: "спрашивать" },
  { id: 42, word: "odgovarati", uk: "відповідати", ru: "отвечать" },
  { id: 43, word: "razgovarati", uk: "розмовляти", ru: "разговаривать" },
  { id: 44, word: "diskutovati", uk: "дискутувати", ru: "дискутировать" },
  { id: 45, word: "objašnjavati", uk: "пояснювати", ru: "объяснять" },
  { id: 46, word: "slušati", uk: "слухати", ru: "слушать" },
  { id: 47, word: "čuti", uk: "чути", ru: "слышать" },
  { id: 48, word: "gledati", uk: "дивитися", ru: "смотреть" },
  { id: 49, word: "posmatrati", uk: "спостерігати", ru: "наблюдать" },
  { id: 50, word: "pokazivati", uk: "показувати", ru: "показывать" },
  { id: 51, word: "pisati", uk: "писати", ru: "писать" },
  { id: 52, word: "crtati", uk: "малювати", ru: "рисовать" },
  { id: 53, word: "slikati", uk: "малювати/фотографувати", ru: "рисовать/фотографировать" },
  { id: 54, word: "fotografisati", uk: "фотографувати", ru: "фотографировать" },
  { id: 55, word: "snimati", uk: "знімати (відео/аудіо)", ru: "снимать (видео/аудио)" },
  { id: 56, word: "snimiti", uk: "зняти/записати", ru: "записать" },
  { id: 57, word: "pričati", uk: "розповідати", ru: "рассказывать" },
  { id: 58, word: "govoriti", uk: "говорити", ru: "говорить" },
  { id: 59, word: "lagati", uk: "брехати", ru: "лгать" },
  { id: 60, word: "obećati", uk: "обіцяти", ru: "обещать" },
  { id: 61, word: "slagati se", uk: "погоджуватися", ru: "соглашаться" },
  { id: 62, word: "neslagati se", uk: "не погоджуватися", ru: "не соглашаться" },
  { id: 63, word: "svađati se", uk: "сваритися", ru: "ссориться" },
  { id: 64, word: "dogovarati se", uk: "домовлятися", ru: "договариваться" },
  { id: 65, word: "prihvatiti", uk: "прийняти", ru: "принять" },
  { id: 66, word: "odbijati", uk: "відмовляти", ru: "отказывать" },
  { id: 67, word: "radovati se", uk: "радіти", ru: "радоваться" },
  { id: 68, word: "smejati se", uk: "сміятися", ru: "смеяться" },
  { id: 69, word: "plakati", uk: "плакати", ru: "плакать" },
  { id: 70, word: "ljutiti se", uk: "сердитися", ru: "злиться" },
  { id: 71, word: "mrzeti", uk: "ненавидіти", ru: "ненавидеть" },
  { id: 72, word: "voleti", uk: "любити", ru: "любить" },
  { id: 73, word: "voleti se", uk: "любитися", ru: "любить друг друга" },
  { id: 74, word: "nedostajati", uk: "не вистачати", ru: "скучать/не хватать" },
  { id: 75, word: "nadati se", uk: "сподіватися", ru: "надеяться" },
  { id: 76, word: "bojati se", uk: "боятися", ru: "бояться" },
  { id: 77, word: "čuditi se", uk: "дивуватися", ru: "удивляться" },
  { id: 78, word: "zanimati se", uk: "цікавитися", ru: "интересоваться" },
  { id: 79, word: "želeti", uk: "хотіти", ru: "хотеть" },
  { id: 80, word: "misliti", uk: "думати", ru: "думать" },
  { id: 81, word: "razmišljati", uk: "розмірковувати", ru: "размышлять" },
  { id: 82, word: "odlučiti", uk: "вирішити", ru: "решить" },
  { id: 83, word: "izabrati", uk: "вибрати", ru: "выбрать" },
  { id: 84, word: "probati", uk: "пробувати", ru: "пробовать" },
  { id: 85, word: "pokušati", uk: "намагатися", ru: "пытаться" },
  { id: 86, word: "uspeti", uk: "вдатися", ru: "удаться" },
  { id: 87, word: "učiti", uk: "вчити", ru: "учить" },
  { id: 88, word: "naučiti", uk: "вивчити", ru: "выучить" },
  { id: 89, word: "studirati", uk: "вивчати/навчатися", ru: "изучать/учиться" },
  { id: 90, word: "predavati", uk: "викладати", ru: "преподавать" },
  { id: 91, word: "raditi", uk: "працювати", ru: "работать" },
  { id: 92, word: "zaraditi", uk: "заробити", ru: "заработать" },
  { id: 93, word: "odmarati se", uk: "відпочивати", ru: "отдыхать" },
  { id: 94, word: "putovati", uk: "подорожувати", ru: "путешествовать" },
  { id: 95, word: "organizovati", uk: "організовувати", ru: "организовывать" },
  { id: 96, word: "planirati", uk: "планувати", ru: "планировать" },
  { id: 97, word: "voditi", uk: "вести/керувати", ru: "вести/руководить" },
  { id: 98, word: "upravljati", uk: "керувати/кермувати", ru: "управлять" },
  { id: 99, word: "upisati", uk: "записати/вписати", ru: "записать" },
  { id: 100, word: "brisati", uk: "витирати/видаляти", ru: "стирать/удалять" },
  { id: 101, word: "sačuvati", uk: "зберегти", ru: "сохранить" },
  { id: 102, word: "preuzeti", uk: "завантажити", ru: "скачать" },
  { id: 103, word: "učitati", uk: "завантажити (вгору)", ru: "загрузить" },
  { id: 104, word: "povezati", uk: "з’єднати", ru: "соединить" },
  { id: 105, word: "instalirati", uk: "встановити", ru: "установить" },
  { id: 106, word: "popraviti", uk: "полагодити", ru: "починить" },
  { id: 107, word: "razbiti", uk: "розбити", ru: "разбить" },
  { id: 108, word: "slomiti", uk: "зламати", ru: "сломать" },
  { id: 109, word: "praviti", uk: "робити/створювати", ru: "делать/создавать" },
  { id: 110, word: "koristiti", uk: "використовувати", ru: "использовать" },
  { id: 111, word: "pomagati", uk: "допомагати", ru: "помогать" },
  { id: 112, word: "poslužiti", uk: "подавати/служити", ru: "подать/послужить" },
  { id: 113, word: "početi", uk: "почати", ru: "начать" },
  { id: 114, word: "započeti", uk: "розпочати", ru: "начинать" },
  { id: 115, word: "nastaviti", uk: "продовжити", ru: "продолжить" },
  { id: 116, word: "završiti", uk: "закінчити", ru: "закончить" },
  { id: 117, word: "prestati", uk: "припинити", ru: "прекратить" },
  { id: 118, word: "trajati", uk: "тривати", ru: "длиться" },
  { id: 119, word: "postojati", uk: "існувати", ru: "существовать" },
  { id: 120, word: "živeti", uk: "жити", ru: "жить" },
  { id: 121, word: "buditi se", uk: "прокидатися", ru: "просыпаться" },
  { id: 122, word: "ustati", uk: "піднятися/встати", ru: "встать" },
  { id: 123, word: "leći", uk: "лягти", ru: "лечь" },
  { id: 124, word: "spavati", uk: "спати", ru: "спать" },
  { id: 125, word: "odspavati", uk: "подрімати", ru: "вздремнуть" },
  { id: 126, word: "umivati se", uk: "умиватися", ru: "умываться" },
  { id: 127, word: "tuširati se", uk: "приймати душ", ru: "принимать душ" },
  { id: 128, word: "kupati se", uk: "купатися/купати", ru: "купаться" },
  { id: 129, word: "oblačiti se", uk: "одягатися", ru: "одеваться" },
  { id: 130, word: "svlačiti se", uk: "роздягатися", ru: "раздеваться" },
  { id: 131, word: "presvlačiti se", uk: "переодягатися", ru: "переодеваться" },
  { id: 132, word: "brijati se", uk: "голитися", ru: "бриться" },
  { id: 133, word: "češljati se", uk: "чесатися", ru: "причёсываться" },
  { id: 134, word: "šminkati se", uk: "фарбуватися", ru: "краситься" },
  { id: 135, word: "hraniti se", uk: "харчуватися", ru: "питаться" },
  { id: 136, word: "večerati", uk: "вечеряти", ru: "ужинать" },
  { id: 137, word: "ručati", uk: "обідати", ru: "обедать" },
  { id: 138, word: "doručkovati", uk: "снідати", ru: "завтракать" },
  { id: 139, word: "gladovati", uk: "голодувати", ru: "голодать" },
  { id: 140, word: "žeđati", uk: "хотіти пити", ru: "жаждать" },
  { id: 141, word: "kupovati namirnice", uk: "купувати продукти", ru: "покупать продукты" },
  { id: 142, word: "stizati", uk: "прибувати/доходити", ru: "прибывать" },
  { id: 143, word: "polaziti", uk: "вирушати", ru: "отправляться" },
  { id: 144, word: "dolaziti", uk: "приходити", ru: "приходить" },
  { id: 145, word: "odlaziti", uk: "йти/відходити", ru: "уходить" },
  { id: 146, word: "putovati vozom", uk: "їхати потягом", ru: "ехать поездом" },
  { id: 147, word: "leteti avionom", uk: "летіти літаком", ru: "лететь самолётом" },
  { id: 148, word: "ploviti", uk: "плисти/плавати", ru: "плыть" },
  { id: 149, word: "voziti motor", uk: "їздити на мотоциклі", ru: "ездить на мотоцикле" },
  { id: 150, word: "voziti čamac", uk: "керувати човном", ru: "водить лодку" },
  { id: 151, word: "šetati", uk: "гуляти", ru: "гулять" },
  { id: 152, word: "šetati psa", uk: "вигулювати собаку", ru: "выгуливать собаку" },
  { id: 153, word: "juriti", uk: "гнати/бігти", ru: "гнаться/мчаться" },
  { id: 154, word: "bežati", uk: "тікати", ru: "убегать" },
  { id: 155, word: "pobeći", uk: "втекти", ru: "сбежать" },
  { id: 156, word: "stići", uk: "дістатися", ru: "достичь/успеть" },
  { id: 157, word: "sećati se", uk: "пам’ятати", ru: "помнить" },
  { id: 158, word: "zaboraviti", uk: "забути", ru: "забыть" },
  { id: 159, word: "podsećati", uk: "нагадувати", ru: "напоминать" },
  { id: 160, word: "razumeti", uk: "розуміти", ru: "понимать" },
  { id: 161, word: "shvatiti", uk: "зрозуміти/усвідомити", ru: "осознать/понять" },
  { id: 162, word: "uvideti", uk: "усвідомити", ru: "увидеть/осознать" },
  { id: 163, word: "verovati", uk: "вірити", ru: "верить" },
  { id: 164, word: "sumnjati", uk: "сумніватися", ru: "сомневаться" },
  { id: 165, word: "maštati", uk: "мріяти/фантазувати", ru: "мечтать" },
  { id: 166, word: "sanjariti", uk: "марити/фантазувати", ru: "мечтать" },
  { id: 167, word: "pamtiti", uk: "запам’ятовувати", ru: "запоминать" },
  { id: 168, word: "zamisliti", uk: "уявити", ru: "вообразить" },
  { id: 169, word: "predstavljati", uk: "представляти", ru: "представлять" },
  { id: 170, word: "upoređivati", uk: "порівнювати", ru: "сравнивать" },
  { id: 171, word: "meriti", uk: "міряти/вимірювати", ru: "мерить/измерять" },
  { id: 172, word: "računati", uk: "рахувати", ru: "считать" },
  { id: 173, word: "izračunati", uk: "порахувати", ru: "посчитать" },
  { id: 174, word: "dodati", uk: "додати", ru: "добавить" },
  { id: 175, word: "oduzeti", uk: "відняти", ru: "отнять" },
  { id: 176, word: "množiti", uk: "множити", ru: "умножать" },
  { id: 177, word: "deliti", uk: "ділити", ru: "делить" },
  { id: 178, word: "deliti se", uk: "ділитися", ru: "делиться" },
  { id: 179, word: "sastajati se", uk: "зустрічатися", ru: "встречаться" },
  { id: 180, word: "održavati", uk: "підтримувати/проводити", ru: "поддерживать/проводить" },
  { id: 181, word: "organizovati sastanak", uk: "організовувати зустріч", ru: "организовывать встречу" },
  { id: 182, word: "prisustvovati", uk: "бути присутнім", ru: "присутствовать" },
  { id: 183, word: "učestvovati", uk: "брати участь", ru: "участвовать" },
  { id: 184, word: "dogoditi se", uk: "статися", ru: "случиться" },
  { id: 185, word: "desiti se", uk: "статися", ru: "произойти" },
  { id: 186, word: "izvoditi", uk: "виконувати", ru: "исполнять" },
  { id: 187, word: "izvesti", uk: "виконати", ru: "исполнить" },
  { id: 188, word: "graditi", uk: "будувати", ru: "строить" },
  { id: 189, word: "sagraditi", uk: "побудувати", ru: "построить" },
  { id: 190, word: "rušiti", uk: "руйнувати", ru: "разрушать" },
  { id: 191, word: "popravljati", uk: "лагодити/ремонтувати", ru: "чинить/ремонтировать" },
  { id: 192, word: "krečiti", uk: "білювати/фарбувати", ru: "белить/красить" },
  { id: 193, word: "farbati", uk: "фарбувати", ru: "красить" },
  { id: 194, word: "sejati", uk: "сіяти", ru: "сеять" },
  { id: 195, word: "saditi", uk: "садити", ru: "сажать" },
  { id: 196, word: "zalivati", uk: "поливати", ru: "поливать" },
  { id: 197, word: "žnjeti", uk: "жати", ru: "жать" },
  { id: 198, word: "brati", uk: "збирати/рвати", ru: "собирать/рвать" },
  { id: 199, word: "zadovoljiti", uk: "задовольнити", ru: "удовлетворить" },
  { id: 200, word: "zadovoljavati", uk: "задовольняти", ru: "удовлетворять" },
  { id: 201, word: "uživati", uk: "насолоджуватися", ru: "наслаждаться" },
  { id: 202, word: "iznenaditi", uk: "здивувати", ru: "удивить" },
  { id: 203, word: "iznenađivati", uk: "дивувати", ru: "удивлять" },
  { id: 204, word: "čuditi", uk: "дивувати", ru: "удивлять" },
  { id: 205, word: "mrzeti se", uk: "ненавидітися", ru: "ненавидеть друг друга" },
  { id: 206, word: "voleti više", uk: "любити більше", ru: "любить больше" },
  { id: 207, word: "kretati se", uk: "рухатися", ru: "двигаться" },
  { id: 208, word: "zaustaviti", uk: "зупинити", ru: "остановить" },
  { id: 209, word: "zaustavljati", uk: "зупиняти", ru: "останавливать" },
  { id: 210, word: "dodirnuti", uk: "доторкнутися", ru: "потрогать/коснуться" },
  { id: 211, word: "dirati", uk: "чіпати", ru: "трогать" },
  { id: 212, word: "pucati", uk: "стріляти/тріскати", ru: "стрелять/трескаться" },
  { id: 213, word: "gađati", uk: "цілити", ru: "метать/целиться" },
  { id: 214, word: "loviti", uk: "полювати/ловити", ru: "охотиться/ловить" },
  { id: 215, word: "ubiti", uk: "вбити", ru: "убить" },
  { id: 216, word: "raniti", uk: "поранити", ru: "ранить" },
  { id: 217, word: "preživeti", uk: "вижити", ru: "выжить" },
  { id: 218, word: "umreti", uk: "померти", ru: "умереть" },
  { id: 219, word: "roditi se", uk: "народитися", ru: "родиться" },
  { id: 220, word: "živeti zajedno", uk: "жити разом", ru: "жить вместе" },
  { id: 221, word: "postati", uk: "стати", ru: "стать" },
  { id: 222, word: "biti", uk: "бути", ru: "быть" },
  { id: 223, word: "imati", uk: "мати", ru: "иметь" },
  { id: 224, word: "imati potrebu", uk: "мати потребу", ru: "нуждаться" },
  { id: 225, word: "trebati", uk: "потребувати", ru: "нуждаться/быть должным" },
  { id: 226, word: "moći", uk: "могти", ru: "мочь" },
  { id: 227, word: "morati", uk: "мусити", ru: "долженствовать" },
  { id: 228, word: "smeti", uk: "сміти/мати право", ru: "сметь" },
  { id: 229, word: "dati", uk: "дати", ru: "дать" },
  { id: 230, word: "uzeti", uk: "взяти", ru: "взять" },
  { id: 231, word: "staviti", uk: "поставити/покласти", ru: "поставить/положить" },
  { id: 232, word: "skinuti", uk: "зняти/скачати", ru: "снять/скачать" },
  { id: 233, word: "držati", uk: "тримати", ru: "держать" },
  { id: 234, word: "naći", uk: "знайти", ru: "найти" },
  { id: 235, word: "tražiti", uk: "шукати/вимагати", ru: "искать/требовать" },
  { id: 236, word: "dobiti", uk: "отримати", ru: "получить" },
  { id: 237, word: "dobijati", uk: "отримувати", ru: "получать" },
  { id: 238, word: "hteti", uk: "хотіти (хтіти)", ru: "хотеть" },
  { id: 239, word: "napisati", uk: "написати", ru: "написать" },
  { id: 240, word: "pročitati", uk: "прочитати", ru: "прочитать" },
  { id: 241, word: "pogledati", uk: "подивитися", ru: "посмотреть" },
  { id: 242, word: "kupiti", uk: "купити", ru: "купить" },
  { id: 243, word: "prodati", uk: "продати", ru: "продать" },
  { id: 244, word: "pojesti", uk: "з’їсти", ru: "съесть" },
  { id: 245, word: "popiti", uk: "випити", ru: "выпить" },
  { id: 246, word: "poneti", uk: "понести/взяти з собою", ru: "понести/взять с собой" },
  { id: 247, word: "izneti", uk: "винести", ru: "вынести" },
  { id: 248, word: "uneti", uk: "занести/внести", ru: "внести/занести" }
];

// === SR_NOUNS ===
window.decks.sr_nouns = [
  { id: 1, word: "novac", uk: "гроші", ru: "деньги" },
  { id: 2, word: "biti", uk: "бути", ru: "быть" },
  { id: 3, word: "vreme", uk: "час/погода", ru: "время/погода" },
  { id: 4, word: "imati", uk: "мати", ru: "иметь" },
  { id: 5, word: "godina", uk: "рік", ru: "год" },
  { id: 6, word: "raditi", uk: "працювати/робити", ru: "работать/делать" },
  { id: 7, word: "čovek", uk: "людина", ru: "человек" },
  { id: 8, word: "reći", uk: "сказати", ru: "сказать" },
  { id: 9, word: "žena", uk: "жінка", ru: "женщина" },
  { id: 10, word: "govoriti", uk: "говорити", ru: "говорить" },
  { id: 11, word: "muškarac", uk: "чоловік", ru: "мужчина" },
  { id: 12, word: "videti", uk: "бачити", ru: "видеть" },
  { id: 13, word: "dete", uk: "дитина", ru: "ребёнок" },
  { id: 14, word: "gledati", uk: "дивитися", ru: "смотреть" },
  { id: 15, word: "grad", uk: "місто", ru: "город" },
  { id: 16, word: "čuti", uk: "чути", ru: "слышать" },
  { id: 17, word: "zemlja", uk: "країна/земля", ru: "страна/земля" },
  { id: 18, word: "slušati", uk: "слухати", ru: "слушать" },
  { id: 19, word: "kuća", uk: "будинок", ru: "дом" },
  { id: 20, word: "znati", uk: "знати", ru: "знать" },
  { id: 21, word: "stan", uk: "квартира", ru: "квартира" },
  { id: 22, word: "moći", uk: "могти", ru: "мочь" },
  { id: 23, word: "soba", uk: "кімната", ru: "комната" },
  { id: 24, word: "želeti", uk: "хотіти/бажати", ru: "хотеть/желать" },
  { id: 25, word: "vrata", uk: "двері", ru: "дверь" },
  { id: 26, word: "voleti", uk: "любити", ru: "любить" },
  { id: 27, word: "prozor", uk: "вікно", ru: "окно" },
  { id: 28, word: "misliti", uk: "думати", ru: "думать" },
  { id: 29, word: "stolica", uk: "стілець", ru: "стул" },
  { id: 30, word: "verovati", uk: "вірити", ru: "верить" },
  { id: 31, word: "krevet", uk: "ліжко", ru: "кровать" },
  { id: 32, word: "nadati se", uk: "сподіватися", ru: "надеяться" },
  { id: 33, word: "ormar", uk: "шафа", ru: "шкаф" },
  { id: 34, word: "plašiti se", uk: "боятися", ru: "бояться" },
  { id: 35, word: "lampa", uk: "лампа", ru: "лампа" },
  { id: 36, word: "sećati se", uk: "пам’ятати", ru: "помнить" },
  { id: 37, word: "tepih", uk: "килим", ru: "ковёр" },
  { id: 38, word: "zaboraviti", uk: "забути", ru: "забыть" },
  { id: 39, word: "auto", uk: "авто", ru: "машина" },
  { id: 40, word: "jesti", uk: "їсти", ru: "есть" },
  { id: 41, word: "autobus", uk: "автобус", ru: "автобус" },
  { id: 42, word: "piti", uk: "пити", ru: "пить" },
  { id: 43, word: "voz", uk: "поїзд", ru: "поезд" },
  { id: 44, word: "spavati", uk: "спати", ru: "спать" },
  { id: 45, word: "avion", uk: "літак", ru: "самолёт" },
  { id: 46, word: "ustati", uk: "встати", ru: "встать" },
  { id: 47, word: "brod", uk: "корабель", ru: "корабль" },
  { id: 48, word: "ležati", uk: "лежати", ru: "лежать" },
  { id: 49, word: "bicikl", uk: "велосипед", ru: "велосипед" },
  { id: 50, word: "sedeti", uk: "сидіти", ru: "сидеть" },
  { id: 51, word: "ulica", uk: "вулиця", ru: "улица" },
  { id: 52, word: "stajati", uk: "стояти", ru: "стоять" },
  { id: 53, word: "most", uk: "міст", ru: "мост" },
  { id: 54, word: "hodati", uk: "ходити (пішки)", ru: "ходить" },
  { id: 55, word: "put", uk: "шлях/дорога", ru: "путь/дорога" },
  { id: 56, word: "trčati", uk: "бігти", ru: "бежать" },
  { id: 57, word: "trg", uk: "площа", ru: "площадь" },
  { id: 58, word: "ići", uk: "йти", ru: "идти/ехать" },
  { id: 59, word: "voda", uk: "вода", ru: "вода" },
  { id: 60, word: "doći", uk: "прийти", ru: "прийти" },
  { id: 61, word: "hleb", uk: "хліб", ru: "хлеб" },
  { id: 62, word: "otići", uk: "піти/піти геть", ru: "уйти" },
  { id: 63, word: "mleko", uk: "молоко", ru: "молоко" },
  { id: 64, word: "ulaziti", uk: "заходити", ru: "входить" },
  { id: 65, word: "sir", uk: "сир", ru: "сыр" },
  { id: 66, word: "izlaziti", uk: "виходити", ru: "выходить" },
  { id: 67, word: "meso", uk: "м’ясо", ru: "мясо" },
  { id: 68, word: "nositi", uk: "носити", ru: "носить" },
  { id: 69, word: "riba", uk: "риба", ru: "рыба" },
  { id: 70, word: "doneti", uk: "принести", ru: "принести" },
  { id: 71, word: "povrće", uk: "овочі", ru: "овощи" },
  { id: 72, word: "odneti", uk: "віднести", ru: "унести/отнести" },
  { id: 73, word: "voće", uk: "фрукти", ru: "фрукты" },
  { id: 74, word: "voziti", uk: "керувати/вести", ru: "водить (машину)" },
  { id: 75, word: "jabuka", uk: "яблуко", ru: "яблоко" },
  { id: 76, word: "voziti se", uk: "їхати", ru: "ехать" },
  { id: 77, word: "banana", uk: "банан", ru: "банан" },
  { id: 78, word: "putovati", uk: "подорожувати", ru: "путешествовать" },
  { id: 79, word: "posao", uk: "робота", ru: "работа" },
  { id: 80, word: "zanimanje", uk: "професія", ru: "профессия" },
  { id: 81, word: "praviti", uk: "робити/створювати", ru: "делать/создавать" },
  { id: 82, word: "škola", uk: "школа", ru: "школа" },
  { id: 83, word: "kupiti", uk: "купити", ru: "купить" },
  { id: 84, word: "univerzitet", uk: "університет", ru: "университет" },
  { id: 85, word: "prodati", uk: "продати", ru: "продать" },
  { id: 86, word: "učitelj", uk: "вчитель", ru: "учитель" },
  { id: 87, word: "platiti", uk: "заплатити", ru: "заплатить" },
  { id: 88, word: "učenik", uk: "учень", ru: "ученик" },
  { id: 89, word: "dobiti", uk: "отримати", ru: "получить" },
  { id: 90, word: "student", uk: "студент", ru: "студент" },
  { id: 91, word: "dati", uk: "дати", ru: "дать" },
  { id: 92, word: "knjiga", uk: "книга", ru: "книга" },
  { id: 93, word: "uzeti", uk: "взяти", ru: "взять" },
  { id: 94, word: "novine", uk: "газета", ru: "газета" },
  { id: 95, word: "otvoriti", uk: "відкрити", ru: "открыть" },
  { id: 96, word: "sveska", uk: "зошит", ru: "тетрадь" },
  { id: 97, word: "zatvoriti", uk: "закрити", ru: "закрыть" },
  { id: 98, word: "računar", uk: "комп’ютер", ru: "компьютер" },
  { id: 99, word: "čitati", uk: "читати", ru: "читать" },
  { id: 100, word: "laptop", uk: "ноутбук", ru: "ноутбук" },
  { id: 101, word: "pisati", uk: "писати", ru: "писать" },
  { id: 102, word: "telefon", uk: "телефон", ru: "телефон" },
  { id: 103, word: "učiti", uk: "вчити", ru: "учить" },
  { id: 104, word: "internet", uk: "інтернет", ru: "интернет" },
  { id: 105, word: "naučiti", uk: "вивчити", ru: "выучить" },
  { id: 106, word: "monitor", uk: "екран/монітор", ru: "экран/монитор" },
  { id: 107, word: "pamtiti", uk: "пам’ятати", ru: "запоминать" },
  { id: 108, word: "miš", uk: "миша", ru: "мышь" },
  { id: 109, word: "pitati", uk: "питати", ru: "спрашивать" },
  { id: 110, word: "tastatura", uk: "клавіатура", ru: "клавиатура" },
  { id: 111, word: "odgovoriti", uk: "відповісти", ru: "ответить" },
  { id: 112, word: "štampač", uk: "принтер", ru: "принтер" },
  { id: 113, word: "objasniti", uk: "пояснити", ru: "объяснить" },
  { id: 114, word: "aplikacija", uk: "додаток", ru: "приложение" },
  { id: 115, word: "razumeti", uk: "розуміти", ru: "понимать" },
  { id: 116, word: "program", uk: "програма", ru: "программа" },
  { id: 117, word: "porodica", uk: "родина", ru: "семья" },
  { id: 118, word: "igrati", uk: "грати", ru: "играть" },
  { id: 119, word: "otac", uk: "батько", ru: "отец" },
  { id: 120, word: "plesati", uk: "танцювати", ru: "танцевать" },
  { id: 121, word: "majka", uk: "мати", ru: "мать" },
  { id: 122, word: "pevati", uk: "співати", ru: "петь" },
  { id: 123, word: "sin", uk: "син", ru: "сын" },
  { id: 124, word: "ćerka", uk: "дочка", ru: "дочь" },
  { id: 125, word: "svirati", uk: "грати (на інстр.)", ru: "играть (на муз. инструменте)" },
  { id: 126, word: "brat", uk: "брат", ru: "брат" },
  { id: 127, word: "kuvati", uk: "готувати", ru: "готовить" },
  { id: 128, word: "sestra", uk: "сестра", ru: "сестра" },
  { id: 129, word: "čistiti", uk: "чистити", ru: "чистить/убирать" },
  { id: 130, word: "prijatelj", uk: "друг", ru: "друг" },
  { id: 131, word: "prati", uk: "мити/прати", ru: "мыть/стирать" },
  { id: 132, word: "prijateljica", uk: "подруга", ru: "подруга" },
  { id: 133, word: "sušiti", uk: "сушити", ru: "сушить" },
  { id: 134, word: "roditelji", uk: "батьки", ru: "родители" },
  { id: 135, word: "peći", uk: "пекти", ru: "печь" },
  { id: 136, word: "hrana", uk: "їжа", ru: "еда" },
  { id: 137, word: "početi", uk: "почати", ru: "начать" },
  { id: 138, word: "doručak", uk: "сніданок", ru: "завтрак" },
  { id: 139, word: "završiti", uk: "закінчити", ru: "закончить" },
  { id: 140, word: "ručak", uk: "обід", ru: "обед" },
  { id: 141, word: "trajati", uk: "тривати", ru: "длиться" },
  { id: 142, word: "večera", uk: "вечеря", ru: "ужин" },
  { id: 143, word: "ostati", uk: "залишитися", ru: "остаться" },
  { id: 144, word: "piće", uk: "напій", ru: "напиток" },
  { id: 145, word: "promeniti", uk: "змінити", ru: "изменить" },
  { id: 146, word: "sok", uk: "сік", ru: "сок" },
  { id: 147, word: "pokušati", uk: "спробувати", ru: "попробовать" },
  { id: 148, word: "čaj", uk: "чай", ru: "чай" },
  { id: 149, word: "uspeti", uk: "вдалося/успішно", ru: "смочь/преуспеть" },
  { id: 150, word: "kafa", uk: "кава", ru: "кофе" },
  { id: 151, word: "pobediti", uk: "перемогти", ru: "победить" },
  { id: 152, word: "pivo", uk: "пиво", ru: "пиво" },
  { id: 153, word: "izgubiti", uk: "втратити/програти", ru: "потерять/проиграть" },
  { id: 154, word: "vino", uk: "вино", ru: "вино" },
  { id: 155, word: "naći", uk: "знайти", ru: "найти" },
  { id: 156, word: "lekar", uk: "лікар", ru: "врач" },
  { id: 157, word: "tražiti", uk: "шукати", ru: "искать" },
  { id: 158, word: "klinika", uk: "клініка", ru: "клиника" },
  { id: 159, word: "čekati", uk: "чекати", ru: "ждать" },
  { id: 160, word: "bolnica", uk: "лікарня", ru: "больница" },
  { id: 161, word: "pozvati", uk: "покликати/подзвонити", ru: "позвать/позвонить" },
  { id: 162, word: "tableta", uk: "таблетка", ru: "таблетка" },
  { id: 163, word: "dozvoliti", uk: "дозволити", ru: "разрешить" },
  { id: 164, word: "lek", uk: "ліки", ru: "лекарство" },
  { id: 165, word: "zabraniti", uk: "заборонити", ru: "запретить" },
  { id: 166, word: "zdravlje", uk: "здоров’я", ru: "здоровье" },
  { id: 167, word: "morati", uk: "мусити", ru: "долженствовать" },
  { id: 168, word: "bolest", uk: "хвороба", ru: "болезнь" },
  { id: 169, word: "trebati", uk: "потрібно", ru: "нужно" },
  { id: 170, word: "bol", uk: "біль", ru: "боль" },
  { id: 171, word: "pomoć", uk: "допомога", ru: "помощь" },
  { id: 172, word: "čuvati", uk: "берегти/охороняти", ru: "хранить/беречь" },
  { id: 173, word: "osiguranje", uk: "страхування", ru: "страховка" },
  { id: 174, word: "koristiti", uk: "користуватися", ru: "использовать" },
  { id: 175, word: "sunce", uk: "сонце", ru: "солнце" },
  { id: 176, word: "mesec", uk: "місяць", ru: "луна/місяць" },
  { id: 177, word: "leteti", uk: "літати", ru: "летать" },
  { id: 178, word: "zvezda", uk: "зірка", ru: "звезда" },
  { id: 179, word: "plivati", uk: "плавати", ru: "плавать" },
  { id: 180, word: "kiša", uk: "дощ", ru: "дождь" },
  { id: 181, word: "pasti", uk: "падати", ru: "падать" },
  { id: 182, word: "sneg", uk: "сніг", ru: "снег" },
  { id: 183, word: "skočiti", uk: "стрибнути", ru: "прыгнуть" },
  { id: 184, word: "vetar", uk: "вітер", ru: "ветер" },
  { id: 185, word: "držati", uk: "тримати", ru: "держать" },
  { id: 186, word: "oblak", uk: "хмара", ru: "облако" },
  { id: 187, word: "baciti", uk: "кинути", ru: "бросить" },
  { id: 188, word: "nebo", uk: "небо", ru: "небо" },
  { id: 189, word: "udariti", uk: "вдарити", ru: "ударить" },
  { id: 190, word: "temperatura", uk: "температура", ru: "температура" },
  { id: 191, word: "pomeriti", uk: "пересунути", ru: "передвинуть" },
  { id: 192, word: "proleće", uk: "весна", ru: "весна" },
  { id: 193, word: "okrenuti", uk: "повернути", ru: "повернуть" },
  { id: 194, word: "leto", uk: "літо", ru: "лето" },
  { id: 195, word: "jesen", uk: "осінь", ru: "осень" },
  { id: 196, word: "zima", uk: "зима", ru: "зима" },
  { id: 197, word: "nedelja", uk: "тиждень/неділя", ru: "неделя/воскресенье" },
  { id: 198, word: "ponedeljak", uk: "понеділок", ru: "понедельник" },
  { id: 199, word: "utorak", uk: "вівторок", ru: "вторник" },
  { id: 200, word: "sreda", uk: "середа", ru: "среда" },
  { id: 201, word: "četvrtak", uk: "четвер", ru: "четверг" },
  { id: 202, word: "petak", uk: "п’ятниця", ru: "пятница" },
  { id: 203, word: "subota", uk: "субота", ru: "суббота" },
  { id: 204, word: "nedelja (denь)", uk: "неділя (день)", ru: "воскресенье" },
  { id: 205, word: "glava", uk: "голова", ru: "голова" },
  { id: 206, word: "lice", uk: "обличчя", ru: "лицо" },
  { id: 207, word: "nos", uk: "ніс", ru: "нос" },
  { id: 208, word: "usta", uk: "рот", ru: "рот" },
  { id: 209, word: "uho", uk: "вухо", ru: "ухо" },
  { id: 210, word: "vrat", uk: "шия", ru: "шея" },
  { id: 211, word: "rame", uk: "плече", ru: "плечо" },
  { id: 212, word: "ruka", uk: "рука/долоня", ru: "рука/ладонь" },
  { id: 213, word: "prst", uk: "палець", ru: "палец" },
  { id: 214, word: "noga", uk: "нога", ru: "нога" },
  { id: 215, word: "koleno", uk: "коліно", ru: "колено" },
  { id: 216, word: "stopalo", uk: "ступня", ru: "ступня" },
  { id: 217, word: "srce", uk: "серце", ru: "сердце" },
  { id: 218, word: "krv", uk: "кров", ru: "кровь" },
  { id: 219, word: "telo", uk: "тіло", ru: "тело" },
  { id: 220, word: "glad", uk: "голод", ru: "голод" },
  { id: 221, word: "žeđ", uk: "спрага", ru: "жажда" },
  { id: 222, word: "umor", uk: "втома", ru: "усталость" },
  { id: 223, word: "kuvar", uk: "кухар", ru: "повар" },
  { id: 224, word: "konobar", uk: "офіціант", ru: "официант" },
  { id: 225, word: "prodavac", uk: "продавець", ru: "продавец" },
  { id: 226, word: "vozač", uk: "водій", ru: "водитель" },
  { id: 227, word: "inženjer", uk: "інженер", ru: "инженер" },
  { id: 228, word: "programer", uk: "програміст", ru: "программист" },
  { id: 229, word: "menadžer", uk: "менеджер", ru: "менеджер" },
  { id: 230, word: "račun", uk: "рахунок", ru: "счёт" },
  { id: 231, word: "karta", uk: "квиток/карта", ru: "билет/карта" },
  { id: 232, word: "ulaz", uk: "вхід", ru: "вход" },
  { id: 233, word: "izlaz", uk: "вихід", ru: "выход" },
  { id: 234, word: "pomoćnik", uk: "помічник", ru: "помощник" },
  { id: 235, word: "gazda", uk: "хазяїн/власник", ru: "хозяин/владелец" },
  { id: 236, word: "gost", uk: "гість", ru: "гость" },
  { id: 237, word: "stanica", uk: "станція", ru: "станция" },
  { id: 238, word: "aerodrom", uk: "аеропорт", ru: "аэропорт" },
  { id: 239, word: "taksi", uk: "таксі", ru: "такси" },
  { id: 240, word: "vožnja", uk: "їзда/поездка", ru: "поездка" },
  { id: 241, word: "let", uk: "політ", ru: "полёт" },
  { id: 242, word: "putovanje", uk: "подорож", ru: "путешествие" },
  { id: 243, word: "ulaznica", uk: "квиток (вхід)", ru: "входной билет" },
  { id: 244, word: "red", uk: "черга/порядок", ru: "очередь/порядок" },
  { id: 245, word: "cena", uk: "ціна", ru: "цена" },
  { id: 246, word: "novčanik", uk: "гаманець", ru: "кошелёк" },
  { id: 247, word: "kartica", uk: "картка", ru: "карта (платёжная)" },
  { id: 248, word: "prodavnica", uk: "крамниця/магазин", ru: "магазин" },
  { id: 249, word: "market", uk: "ринок/маркет", ru: "рынок/маркет" },
  { id: 250, word: "tržni centar", uk: "торговий центр", ru: "торговый центр" },
  { id: 251, word: "polica", uk: "полиця", ru: "полка" },
  { id: 252, word: "kesa", uk: "пакет", ru: "пакет" },
  { id: 253, word: "gradilište", uk: "будмайданчик", ru: "стройплощадка" },
  { id: 254, word: "zgrada", uk: "будівля", ru: "здание" },
  { id: 255, word: "lift", uk: "ліфт", ru: "лифт" },
  { id: 256, word: "stepenice", uk: "сходи", ru: "лестница" },
  { id: 257, word: "vrtić", uk: "дитсадок", ru: "детсад" },
  { id: 258, word: "bolesnik", uk: "хворий (людина)", ru: "больной (чел.)" },
  { id: 259, word: "kupatilo", uk: "ванна кімната", ru: "ванная" },
  { id: 260, word: "kuhinja", uk: "кухня", ru: "кухня" },
  { id: 261, word: "dnevna soba", uk: "вітальня", ru: "гостиная" },
  { id: 262, word: "spavaća soba", uk: "спальня", ru: "спальня" },
  { id: 263, word: "frižider", uk: "холодильник", ru: "холодильник" },
  { id: 264, word: "šporet", uk: "плита", ru: "плита" },
  { id: 265, word: "sudopera", uk: "мийка", ru: "раковина (кух.)" },
  { id: 266, word: "mašina za veš", uk: "пральна машина", ru: "стиральная машина" },
  { id: 267, word: "usisivač", uk: "пилосос", ru: "пылесос" },
  { id: 268, word: "pegla", uk: "праска", ru: "утюг" },
  { id: 269, word: "daljinski", uk: "пульт", ru: "пульт" },
  { id: 270, word: "punjač", uk: "зарядний пристрій", ru: "зарядное устройство" },
  { id: 271, word: "kabl", uk: "кабель", ru: "кабель" },
  { id: 272, word: "utičnica", uk: "розетка", ru: "розетка" },
  { id: 273, word: "dokument", uk: "документ", ru: "документ" },
  { id: 274, word: "ugovor", uk: "договір", ru: "договор" },
  { id: 275, word: "potpis", uk: "підпис", ru: "подпись" },
  { id: 276, word: "pošta", uk: "пошта", ru: "почта" },
  { id: 277, word: "paket", uk: "пакунок/посилка", ru: "посылка" },
  { id: 278, word: "poruka", uk: "повідомлення", ru: "сообщение" },
  { id: 279, word: "poziv", uk: "дзвінок/запрошення", ru: "звонок/приглашение" },
  { id: 280, word: "sastanak", uk: "зустріч", ru: "встреча" },
  { id: 281, word: "dogovor", uk: "домовленість", ru: "договорённость" },
  { id: 282, word: "razgovor", uk: "розмова", ru: "разговор" },
  { id: 283, word: "ideja", uk: "ідея", ru: "идея" },
  { id: 284, word: "plan", uk: "план", ru: "план" },
  { id: 285, word: "cilj", uk: "мета", ru: "цель" },
  { id: 286, word: "problem", uk: "проблема", ru: "проблема" },
  { id: 287, word: "rešenje", uk: "рішення/вирішення", ru: "решение" },
  { id: 288, word: "uslov", uk: "умова", ru: "условие" },
  { id: 289, word: "pravilo", uk: "правило", ru: "правило" },
  { id: 290, word: "primer", uk: "приклад", ru: "пример" },
  { id: 291, word: "pitanje", uk: "питання", ru: "вопрос" },
  { id: 292, word: "odgovor", uk: "відповідь", ru: "ответ" },
  { id: 293, word: "restoran", uk: "ресторан", ru: "ресторан" },
  { id: 294, word: "kafić", uk: "кафе", ru: "кафе" },
  { id: 295, word: "meni", uk: "меню", ru: "меню" },
  { id: 296, word: "porudžbina", uk: "замовлення", ru: "заказ" },
  { id: 297, word: "kasa", uk: "каса", ru: "касса" },
  { id: 298, word: "sto (rest.)", uk: "стіл (рест.)", ru: "стол (рест.)" },
  { id: 299, word: "konobarica", uk: "офіціантка", ru: "официантка" },
  { id: 300, word: "račun (v restoranі)", uk: "рахунок (у рест.)", ru: "счёт (в рест.)" },
  { id: 301, word: "napojnica", uk: "чайові", ru: "чаевые" },
  { id: 302, word: "jaje", uk: "яйце", ru: "яйцо" },
  { id: 303, word: "piletina", uk: "курятина", ru: "курица (мясо)" },
  { id: 304, word: "govedina", uk: "яловичина", ru: "говядина" },
  { id: 305, word: "svinjetina", uk: "свинина", ru: "свинина" },
  { id: 306, word: "supa", uk: "суп", ru: "суп" },
  { id: 307, word: "čorba", uk: "юшка/чорба", ru: "похлёбка/чорба" },
  { id: 308, word: "salata", uk: "салат", ru: "салат" },
  { id: 309, word: "pirinač", uk: "рис", ru: "рис" },
  { id: 310, word: "testenina", uk: "паста/макарони", ru: "паста/макароны" },
  { id: 311, word: "krompir", uk: "картопля", ru: "картофель" },
  { id: 312, word: "šargarepa", uk: "морква", ru: "морковь" },
  { id: 313, word: "luk", uk: "цибуля", ru: "лук" },
  { id: 314, word: "beli luk", uk: "часник", ru: "чеснок" },
  { id: 315, word: "paradajz", uk: "помідор", ru: "помидор" },
  { id: 316, word: "krastavac", uk: "огірок", ru: "огурец" },
  { id: 317, word: "paprika", uk: "перець", ru: "перец" },
  { id: 318, word: "ulje", uk: "олія", ru: "масло (раст.)" },
  { id: 319, word: "puter", uk: "масло вершкове", ru: "масло сливочное" },
  { id: 320, word: "šećer", uk: "цукор", ru: "сахар" },
  { id: 321, word: "so", uk: "сіль", ru: "соль" },
  { id: 322, word: "brašno", uk: "борошно", ru: "мука" },
  { id: 323, word: "kolač", uk: "тістечко/пиріг", ru: "пирожное/пирог" },
  { id: 324, word: "desert", uk: "десерт", ru: "десерт" },
  { id: 325, word: "sladoled", uk: "морозиво", ru: "мороженое" },
  { id: 326, word: "začin", uk: "спеція/приправа", ru: "специя/приправа" },
  { id: 327, word: "sirće", uk: "оцет", ru: "уксус" },
  { id: 328, word: "voda gazirana", uk: "вода газована", ru: "вода газированная" },
  { id: 329, word: "voda negazirana", uk: "вода негазована", ru: "вода негазированная" },
  { id: 330, word: "restroom/toalet", uk: "туалет", ru: "туалет" },
  { id: 331, word: "odeća", uk: "одяг", ru: "одяг" },
  { id: 332, word: "košulja", uk: "сорочка", ru: "рубашка" },
  { id: 333, word: "majica", uk: "футболка", ru: "футболка" },
  { id: 334, word: "pantalone", uk: "штани", ru: "штаны" },
  { id: 335, word: "farmerke", uk: "джинси", ru: "джинсы" },
  { id: 336, word: "haljina", uk: "сукня", ru: "платье" },
  { id: 337, word: "suknja", uk: "спідниця", ru: "юбка" },
  { id: 338, word: "jakna", uk: "куртка", ru: "куртка" },
  { id: 339, word: "kaput", uk: "пальто", ru: "пальто" },
  { id: 340, word: "džemper", uk: "светр", ru: "свитер" },
  { id: 341, word: "cipele", uk: "туфлі", ru: "туфли" },
  { id: 342, word: "patike", uk: "кросівки", ru: "кроссовки" },
  { id: 343, word: "čizme", uk: "чоботи", ru: "сапоги" },
  { id: 344, word: "čarape", uk: "шкарпетки", ru: "носки" },
  { id: 345, word: "kapa", uk: "шапка", ru: "шапка" },
  { id: 346, word: "šešir", uk: "капелюх", ru: "шляпа" },
  { id: 347, word: "šal", uk: "шарф", ru: "шарф" },
  { id: 348, word: "rukavice", uk: "рукавички", ru: "перчатки" },
  { id: 349, word: "kaiš", uk: "пасок/ремінь", ru: "ремень" },
  { id: 350, word: "veličina", uk: "розмір", ru: "размер" },
  { id: 351, word: "boja", uk: "колір", ru: "цвет" },
  { id: 352, word: "pod", uk: "підлога", ru: "пол" },
  { id: 353, word: "plafon", uk: "стеля", ru: "потолок" },
  { id: 354, word: "zid", uk: "стіна", ru: "стена" },
  { id: 355, word: "ključ", uk: "ключ", ru: "ключ" },
  { id: 356, word: "brava", uk: "замок", ru: "замок" },
  { id: 357, word: "tuš", uk: "душ", ru: "душ" },
  { id: 358, word: "kada", uk: "ванна", ru: "ванна" },
  { id: 359, word: "ogledalo", uk: "дзеркало", ru: "зеркало" },
  { id: 360, word: "peškir", uk: "рушник", ru: "полотенце" },
  { id: 361, word: "sapun", uk: "мило", ru: "мыло" },
  { id: 362, word: "šampon", uk: "шампунь", ru: "шампунь" },
  { id: 363, word: "četkica za zube", uk: "зубна щітка", ru: "зубная щётка" },
  { id: 364, word: "pasta za zube", uk: "зубна паста", ru: "зубная паста" },
  { id: 365, word: "toalet papir", uk: "туалетний папір", ru: "туалетная бумага" },
  { id: 366, word: "tanjir", uk: "тарілка", ru: "тарелка" },
  { id: 367, word: "činija", uk: "миска/чаша", ru: "миска/чаша" },
  { id: 368, word: "čaša", uk: "склянка/фужер", ru: "стакан/бокал" },
  { id: 369, word: "šolja", uk: "чашка", ru: "чашка" },
  { id: 370, word: "kašika", uk: "ложка", ru: "ложка" },
  { id: 371, word: "viljuška", uk: "виделка", ru: "вилка" },
  { id: 372, word: "nož", uk: "ніж", ru: "нож" },
  { id: 373, word: "tiganj", uk: "пательня", ru: "сковорода" },
  { id: 374, word: "šerpa", uk: "каструля", ru: "кастрюля" },
  { id: 375, word: "flaša", uk: "пляшка", ru: "бутылка" },
  { id: 376, word: "kanta", uk: "відро/урна", ru: "ведро/урна" },
  { id: 377, word: "smeće", uk: "сміття", ru: "мусор" },
  { id: 378, word: "metla", uk: "мітла", ru: "метла" },
  { id: 379, word: "krpa", uk: "ганчірка", ru: "тряпка" },
  { id: 380, word: "deterdžent", uk: "засіб для миття", ru: "моющее средство" },
  { id: 381, word: "apoteka", uk: "аптека", ru: "аптека" },
  { id: 382, word: "pekara", uk: "пекарня", ru: "пекарня" },
  { id: 383, word: "mesara", uk: "м’ясна крамниця", ru: "мясная лавка" },
  { id: 384, word: "banka", uk: "банк", ru: "банк" },
  { id: 385, word: "bankomat", uk: "банкомат", ru: "банкомат" },
  { id: 386, word: "muzej", uk: "музей", ru: "музей" },
  { id: 387, word: "pozorište", uk: "театр", ru: "театр" },
  { id: 388, word: "bioskop", uk: "кінотеатр", ru: "кинотеатр" },
  { id: 389, word: "park", uk: "парк", ru: "парк" },
  { id: 390, word: "plaža", uk: "пляж", ru: "пляж" },
  { id: 391, word: "planina", uk: "гора", ru: "гора" },
  { id: 392, word: "šuma", uk: "ліс", ru: "лес" },
  { id: 393, word: "reka", uk: "річка", ru: "река" },
  { id: 394, word: "jezero", uk: "озеро", ru: "озеро" },
  { id: 395, word: "more", uk: "море", ru: "море" },
  { id: 396, word: "selo", uk: "село", ru: "деревня" },
  { id: 397, word: "centar", uk: "центр", ru: "центр" },
  { id: 398, word: "predgrađe", uk: "передмістя", ru: "пригород" },
  { id: 399, word: "adresa", uk: "адреса", ru: "адрес" },
  { id: 400, word: "peron", uk: "перон", ru: "перрон" },
  { id: 401, word: "red vožnje", uk: "розклад руху", ru: "расписание" },
  { id: 402, word: "mapa", uk: "мапа/карта", ru: "карта" },
  { id: 403, word: "pasoš", uk: "паспорт", ru: "паспорт" },
  { id: 404, word: "lična karta", uk: "посвідчення особи", ru: "удостоверение личности" },
  { id: 405, word: "viza", uk: "віза", ru: "виза" },
  { id: 406, word: "prtljag", uk: "багаж", ru: "багаж" },
  { id: 407, word: "kofer", uk: "валіза", ru: "чемодан" },
  { id: 408, word: "ranac", uk: "рюкзак", ru: "рюкзак" },
  { id: 409, word: "torba", uk: "сумка", ru: "сумка" },
  { id: 410, word: "sedište", uk: "місце/сидіння", ru: "место/сиденье" },
  { id: 411, word: "rezervacija", uk: "бронювання", ru: "бронь/резервация" },
  { id: 412, word: "recepcija", uk: "рецепція", ru: "ресепшн" },
  { id: 413, word: "hotel", uk: "готель", ru: "отель" },
  { id: 414, word: "soba (got.)", uk: "номер (гот.)", ru: "номер (от.)" },
  { id: 415, word: "kancelarija", uk: "офіс", ru: "офис" },
  { id: 416, word: "firma", uk: "фірма", ru: "фирма" },
  { id: 417, word: "kompanija", uk: "компанія", ru: "компания" },
  { id: 418, word: "šef", uk: "шеф/керівник", ru: "шеф/начальник" },
  { id: 419, word: "kolega", uk: "колеґа", ru: "коллега" },
  { id: 420, word: "zaposleni", uk: "працівник", ru: "сотрудник" },
  { id: 421, word: "klijent", uk: "клієнт", ru: "клиент" },
  { id: 422, word: "sala (peregovorna)", uk: "переговорна", ru: "переговорная" },
  { id: 423, word: "projekat", uk: "проєкт", ru: "проект" },
  { id: 424, word: "zadatak", uk: "завдання", ru: "задача" },
  { id: 425, word: "rok", uk: "термін/дедлайн", ru: "срок/дедлайн" },
  { id: 426, word: "izveštaj", uk: "звіт", ru: "отчёт" },
  { id: 427, word: "faktura", uk: "рахунок-фактура", ru: "счёт-фактура" },
  { id: 428, word: "porez", uk: "податок", ru: "налог" },
  { id: 429, word: "plata", uk: "зарплата", ru: "зарплата" },
  { id: 430, word: "odmor", uk: "відпустка/відпочинок", ru: "отпуск/отдых" },
  { id: 431, word: "pauza", uk: "перерва", ru: "перерыв" },
  { id: 432, word: "čas", uk: "урок/заняття", ru: "урок/занятие" },
  { id: 433, word: "domaći", uk: "домашнє завдання", ru: "домашнее задание" },
  { id: 434, word: "ispit", uk: "іспит", ru: "экзамен" },
  { id: 435, word: "ocena", uk: "оцінка", ru: "оценка" },
  { id: 436, word: "učionica", uk: "клас/аудиторія", ru: "класс/аудитория" },
  { id: 437, word: "predmet", uk: "предмет", ru: "предмет" },
  { id: 438, word: "jezik", uk: "мова", ru: "язык" },
  { id: 439, word: "rečnik", uk: "словник", ru: "словарь" },
  { id: 440, word: "reč", uk: "слово", ru: "слово" },
  { id: 441, word: "rečenica", uk: "речення", ru: "предложение" },
  { id: 442, word: "tekst", uk: "текст", ru: "текст" },
  { id: 443, word: "vežba", uk: "вправа", ru: "упражнение" },
  { id: 444, word: "test", uk: "тест", ru: "тест" },
  { id: 445, word: "simptom", uk: "симптом", ru: "симптом" },
  { id: 446, word: "groznica", uk: "гарячка/лихоманка", ru: "жар/лихорадка" },
  { id: 447, word: "prehlada", uk: "застуда", ru: "простуда" },
  { id: 448, word: "grip", uk: "грип", ru: "грипп" },
  { id: 449, word: "termin", uk: "запис/термін", ru: "запись/приём" },
  { id: 450, word: "recept (med.)", uk: "рецепт (мед.)", ru: "рецепт (мед.)" },
  { id: 451, word: "hitna pomoć", uk: "швидка допомога", ru: "скорая помощь" },
  { id: 452, word: "ambulanta", uk: "амбулаторія", ru: "амбулатория" },
  { id: 453, word: "sestra (med.)", uk: "медсестра", ru: "медсестра" },
  { id: 454, word: "pacijent", uk: "пацієнт", ru: "пациент" },
  { id: 455, word: "operacija", uk: "операція", ru: "операция" },
  { id: 456, word: "analiza", uk: "аналіз", ru: "анализ" },
  { id: 457, word: "vakcina", uk: "вакцина", ru: "вакцина" },
  { id: 458, word: "sajt", uk: "сайт", ru: "сайт" },
  { id: 459, word: "pregledač", uk: "браузер", ru: "браузер" },
  { id: 460, word: "imejl", uk: "імейл/ел. пошта", ru: "имейл/эл. почта" },
  { id: 461, word: "fajl", uk: "файл", ru: "файл" },
  { id: 462, word: "fascikla", uk: "тека/папка", ru: "папка" },
  { id: 463, word: "slika", uk: "зображення/фото", ru: "картинка/фото" },
  { id: 464, word: "fotografija", uk: "фотографія", ru: "фотография" },
  { id: 465, word: "video", uk: "відео", ru: "видео" },
  { id: 466, word: "muzika", uk: "музика", ru: "музыка" },
  { id: 467, word: "igra", uk: "гра", ru: "игра" },
  { id: 468, word: "nalog", uk: "акаунт/обліковий запис", ru: "аккаунт" },
  { id: 469, word: "lozinka", uk: "пароль", ru: "пароль" },
  { id: 470, word: "podešavanja", uk: "налаштування", ru: "настройки" },
  { id: 471, word: "mreža", uk: "мережа", ru: "сеть" },
  { id: 472, word: "Wi‑Fi", uk: "вай-фай", ru: "вайфай" },
  { id: 473, word: "bluetooth", uk: "блютуз", ru: "блютус" },
  { id: 474, word: "baterija", uk: "акумулятор/батарея", ru: "батарея" },
  { id: 475, word: "kamera", uk: "камера", ru: "камера" },
  { id: 476, word: "mikrofon", uk: "мікрофон", ru: "микрофон" },
  { id: 477, word: "zvučnik", uk: "динамік/колонка", ru: "динамик/колонка" },
  { id: 478, word: "ljubav", uk: "кохання", ru: "любовь" },
  { id: 479, word: "prijateljstvo", uk: "дружба", ru: "дружба" },
  { id: 480, word: "život", uk: "життя", ru: "жизнь" },
  { id: 481, word: "dan", uk: "день", ru: "день" },
  { id: 482, word: "noć", uk: "ніч", ru: "ночь" },
  { id: 483, word: "jutro", uk: "ранок", ru: "утро" },
  { id: 484, word: "veče", uk: "вечір", ru: "вечер" },
  { id: 485, word: "trenutak", uk: "мить/момент", ru: "момент" },
  { id: 486, word: "šansa", uk: "шанс", ru: "шанс" },
  { id: 487, word: "prilika", uk: "нагода/можливість", ru: "возможность/случай" },
  { id: 488, word: "odluka", uk: "рішення", ru: "решение" },
  { id: 489, word: "izbor", uk: "вибір", ru: "выбор" },
  { id: 490, word: "razlog", uk: "причина/підстава", ru: "причина/основание" },
  { id: 491, word: "uzrok", uk: "причина (джерело)", ru: "причина (исток)" },
  { id: 492, word: "rezultat", uk: "результат", ru: "результат" },
  { id: 493, word: "informacija", uk: "інформація", ru: "информация" },
  { id: 494, word: "vest", uk: "новина", ru: "новость" },
  { id: 495, word: "pravo", uk: "право", ru: "право" },
  { id: 496, word: "zakon", uk: "закон", ru: "закон" },
  { id: 497, word: "dozvola", uk: "дозвіл", ru: "разрешение" },
  { id: 498, word: "komšija", uk: "сусід", ru: "сосед" },
  { id: 499, word: "komšinica", uk: "сусідка", ru: "соседка" },
  { id: 500, word: "kupac", uk: "покупець", ru: "покупатель" },
  { id: 501, word: "turista", uk: "турист", ru: "турист" },
  { id: 502, word: "pas", uk: "пес", ru: "собака" },
  { id: 503, word: "mačka", uk: "кіт/кішка", ru: "кошка" },
  { id: 504, word: "ptica", uk: "птах", ru: "птица" },
  { id: 505, word: "krava", uk: "корова", ru: "корова" },
  { id: 506, word: "svinja", uk: "свиня", ru: "свинья" },
  { id: 507, word: "kokoška", uk: "курка", ru: "курица" },
  { id: 508, word: "konj", uk: "кінь", ru: "лошадь" },
  { id: 509, word: "oluja", uk: "буря/гроза", ru: "буря/шторм" },
  { id: 510, word: "magla", uk: "туман", ru: "туман" },
  { id: 511, word: "led", uk: "лід", ru: "лёд" },
  { id: 512, word: "sneg (pokrov)", uk: "сніг (покрив)", ru: "снег (покров)" },
  { id: 513, word: "struja", uk: "електрика/струм", ru: "электричество" },
  { id: 514, word: "gas", uk: "газ", ru: "газ" },
  { id: 515, word: "grejanje", uk: "опалення", ru: "отопление" },
  { id: 516, word: "klima", uk: "кондиціонер", ru: "кондиционер" },
  { id: 517, word: "alat", uk: "інструмент", ru: "инструмент" },
  { id: 518, word: "alatka", uk: "інструмент (дрібн.)", ru: "инструмент (м.)" },
  { id: 519, word: "ekipa", uk: "команда", ru: "команда" },
  { id: 520, word: "tim", uk: "команда", ru: "команда" },
  { id: 521, word: "sport", uk: "спорт", ru: "спорт" },
  { id: 522, word: "utakmica", uk: "матч", ru: "матч" },
  { id: 523, word: "igrač", uk: "гравець", ru: "игрок" },
  { id: 524, word: "lopta", uk: "м’яч", ru: "мяч" },
  { id: 525, word: "vlada", uk: "уряд", ru: "правительство" },
  { id: 526, word: "predsednik", uk: "президент", ru: "президент" },
  { id: 527, word: "ministar", uk: "міністр", ru: "министр" },
  { id: 528, word: "poslanik", uk: "депутат", ru: "депутат" },
  { id: 529, word: "političar", uk: "політик", ru: "политик" },
  { id: 530, word: "izbori", uk: "вибори", ru: "выборы" },
  { id: 531, word: "glas", uk: "голос", ru: "голос" },
  { id: 532, word: "glasanje", uk: "голосування", ru: "голосование" },
  { id: 533, word: "parlament", uk: "парламент", ru: "парламент" },
  { id: 534, word: "država", uk: "держава", ru: "государство" },
  { id: 535, word: "opština", uk: "громада/муніципалітет", ru: "муниципалитет" },
  { id: 536, word: "zakonodavstvo", uk: "законодавство", ru: "законодательство" },
  { id: 537, word: "crkva", uk: "церква", ru: "церковь" },
  { id: 538, word: "manastir", uk: "монастир", ru: "монастырь" },
  { id: 539, word: "džamija", uk: "мечеть", ru: "мечеть" },
  { id: 540, word: "sinagoga", uk: "синагога", ru: "синагога" },
  { id: 541, word: "bog", uk: "бог", ru: "бог" },
  { id: 542, word: "vera", uk: "віра", ru: "вера" },
  { id: 543, word: "molitva", uk: "молитва", ru: "молитва" },
  { id: 544, word: "sveštenik", uk: "священик", ru: "священник" },
  { id: 545, word: "praznik", uk: "свято", ru: "праздник" },
  { id: 546, word: "umetnost", uk: "мистецтво", ru: "искусство" },
  { id: 547, word: "slikar", uk: "художник", ru: "художник" },
  { id: 548, word: "slika (kartina)", uk: "картина", ru: "картина" },
  { id: 549, word: "pesma", uk: "пісня", ru: "песня" },
  { id: 550, word: "književnost", uk: "література", ru: "литература" },
  { id: 551, word: "pozorišna predstava", uk: "театральна вистава", ru: "театральное представление" },
  { id: 552, word: "film", uk: "фільм", ru: "фильм" },
  { id: 553, word: "glumac", uk: "актор", ru: "актёр" },
  { id: 554, word: "glumica", uk: "акторка", ru: "актриса" },
  { id: 555, word: "muzej (iskusstv.)", uk: "музей мистецтв", ru: "музей искусств" },
  { id: 556, word: "volan", uk: "кермо", ru: "руль" },
  { id: 557, word: "točak", uk: "колесо", ru: "колесо" },
  { id: 558, word: "guma", uk: "шина", ru: "шина" },
  { id: 559, word: "kočnica", uk: "гальмо", ru: "тормоз" },
  { id: 560, word: "motor", uk: "двигун", ru: "мотор" },
  { id: 561, word: "gorivo", uk: "паливо", ru: "топливо" },
  { id: 562, word: "benzinska pumpa", uk: "заправка", ru: "заправка" },
  { id: 563, word: "saobraćaj", uk: "рух/трафік", ru: "трафик/движение" },
  { id: 564, word: "semafor", uk: "світлофор", ru: "светофор" },
  { id: 565, word: "saobraćajna nesreća", uk: "аварія", ru: "дтп" },
  { id: 566, word: "vozačka dozvola", uk: "водійські права", ru: "водительские права" },
  { id: 567, word: "ekonomija", uk: "економіка", ru: "экономика" },
  { id: 568, word: "tržište", uk: "ринок", ru: "рынок" },
  { id: 569, word: "berza", uk: "біржа", ru: "биржа" },
  { id: 570, word: "akcija", uk: "акція", ru: "акция" },
  { id: 571, word: "obveznica", uk: "облігація", ru: "облигация" },
  { id: 572, word: "investicija", uk: "інвестиція", ru: "инвестиция" },
  { id: 573, word: "kredit", uk: "кредит", ru: "кредит" },
  { id: 574, word: "dug", uk: "борг", ru: "долг" },
  { id: 575, word: "računovodstvo", uk: "бухгалтерія", ru: "бухгалтерия" },
  { id: 576, word: "budžet", uk: "бюджет", ru: "бюджет" },
  { id: 577, word: "čekić", uk: "молоток", ru: "молоток" },
  { id: 578, word: "odvijač", uk: "викрутка", ru: "отвёртка" },
  { id: 579, word: "ključ (іnstrument)", uk: "гайковий ключ", ru: "гаечный ключ" },
  { id: 580, word: "pila", uk: "пила", ru: "пила" },
  { id: 581, word: "ekser", uk: "цвях", ru: "гвоздь" },
  { id: 582, word: "šraf", uk: "гвинт/болт", ru: "винт/болт" },
  { id: 583, word: "matica", uk: "гайка", ru: "гайка" },
  { id: 584, word: "bušilica", uk: "дриль", ru: "дрель" },
  { id: 585, word: "testera", uk: "пила", ru: "пила (бензо-/електро-)" },
  { id: 586, word: "radost", uk: "радість", ru: "радость" },
  { id: 587, word: "tuga", uk: "смуток", ru: "печаль" },
  { id: 588, word: "bes", uk: "гнів", ru: "гнев" },
  { id: 589, word: "strah", uk: "страх", ru: "страх" },
  { id: 590, word: "iznenađenje", uk: "здивування", ru: "удивление" },
  { id: 591, word: "dosada", uk: "нудьга", ru: "скука" },
  { id: 592, word: "sram", uk: "сором", ru: "стыд" },
  { id: 593, word: "ponos", uk: "гордість", ru: "гордость" },
  { id: 594, word: "sumnja", uk: "сумнів", ru: "сомнение" },
  { id: 595, word: "sigurnost", uk: "безпека/впевненість", ru: "безопасность/уверенность" },
  { id: 596, word: "materijal", uk: "матеріал", ru: "материал" },
  { id: 597, word: "proizvod", uk: "продукт/виріб", ru: "продукт/изделие" },
  { id: 598, word: "usluga", uk: "послуга", ru: "услуга" },
  { id: 599, word: "stvar", uk: "річ", ru: "вещь" },
  { id: 600, word: "pojam", uk: "поняття", ru: "понятие" },
  { id: 601, word: "primerak", uk: "екземпляр", ru: "экземпляр" },
  { id: 602, word: "količina", uk: "кількість", ru: "количество" },
  { id: 603, word: "kvalitet", uk: "якість", ru: "качество" },
  { id: 604, word: "novčana kazna", uk: "грошовий штраф", ru: "денежный штраф" },
  { id: 605, word: "kurs", uk: "курс (валюти)", ru: "курс (валюты)" },
  { id: 606, word: "menjačnica", uk: "обмінник", ru: "обменник валют" },
  { id: 607, word: "kamata", uk: "відсоток (ставка)", ru: "процент (ставка)" },
  { id: 608, word: "račun (ban.)", uk: "рахунок (банк.)", ru: "счёт (банк.)" },
  { id: 609, word: "uplatnica", uk: "квитанція/платіжка", ru: "квитанция/платёжка" },
  { id: 610, word: "osiguranje putno", uk: "страхування подорожнє", ru: "страховка туристическая" },
  { id: 611, word: "kliješta", uk: "плоскогубці", ru: "плоскогубцы" },
  { id: 612, word: "merdevine", uk: "драбина/драбина складна", ru: "лестница-стремянка" },
  { id: 613, word: "kabina tuša", uk: "душова кабіна", ru: "душевая кабина" },
  { id: 614, word: "silikon", uk: "силікон", ru: "силикон" },
  { id: 615, word: "slikarstvo", uk: "живопис", ru: "живопись" },
  { id: 616, word: "skulptura", uk: "скульптура", ru: "скульптура" },
  { id: 617, word: "izložba", uk: "виставка", ru: "выставка" },
  { id: 618, word: "koncert", uk: "концерт", ru: "концерт" },
  { id: 619, word: "festival", uk: "фестиваль", ru: "фестиваль" },
  { id: 620, word: "ulaz besplatan", uk: "вхід вільний", ru: "вход свободный" },
  { id: 621, word: "opštinski ured", uk: "муніципалітет (установа)", ru: "администрация района" },
  { id: 622, word: "ministarstvo", uk: "міністерство", ru: "министерство" },
  { id: 623, word: "glasačko mesto", uk: "виборча дільниця", ru: "избирательный участок" },
  { id: 624, word: "lična karta broj", uk: "номер посвідчення", ru: "номер удостоверения" },
  { id: 625, word: "benzinska stanica", uk: "заправка", ru: "заправка" },
  { id: 626, word: "rezervna guma", uk: "запаска", ru: "запаска" },
  { id: 627, word: "saobraćajna gužva", uk: "затор/пробка", ru: "пробка" },
  { id: 628, word: "saobraćajna policija", uk: "дорожня поліція", ru: "дорожная полиция" },
  { id: 629, word: "parking", uk: "паркінг", ru: "парковка" },
  { id: 630, word: "parking karta", uk: "паркувальний квиток", ru: "парковочный талон" },
  { id: 631, word: "majstor", uk: "майстер", ru: "мастер" },
  { id: 632, word: "električar", uk: "електрик", ru: "электрик" },
  { id: 633, word: "vodoinstalater", uk: "сантехнік", ru: "сантехник" },
  { id: 634, word: "bravar", uk: "слюсар", ru: "слесарь/ключник" },
  { id: 635, word: "čistačica", uk: "прибиральниця", ru: "уборщица" },
  { id: 636, word: "dostava", uk: "доставка", ru: "доставка" },
  { id: 637, word: "kurir", uk: "кур’єр", ru: "курьер" },
  { id: 638, word: "servis", uk: "сервіс/майстерня", ru: "сервис" },
  { id: 639, word: "kilogram", uk: "кілограм", ru: "килограмм" },
  { id: 640, word: "gram", uk: "грам", ru: "грамм" },
  { id: 641, word: "litar", uk: "літр", ru: "литр" },
  { id: 642, word: "mililitar", uk: "мілілітр", ru: "миллилитр" },
  { id: 643, word: "metar", uk: "метр", ru: "метр" },
  { id: 644, word: "centimetar", uk: "сантиметр", ru: "сантиметр" },
  { id: 645, word: "santimetar kvadratni", uk: "квадратний сантиметр", ru: "кв. сантиметр" },
  { id: 646, word: "kvadratni metar", uk: "квадратний метр", ru: "кв. метр" },
  { id: 647, word: "stepen", uk: "градус", ru: "градус" },
  { id: 648, word: "planinarenje", uk: "похід у гори", ru: "альпинизм/походы" },
  { id: 649, word: "pecanje", uk: "рибалка", ru: "рыбалка" },
  { id: 650, word: "šah", uk: "шахи", ru: "шахматы" },
  { id: 651, word: "karte (gra)", uk: "карти (гра)", ru: "карты (игра)" },
  { id: 652, word: "strip", uk: "комікс", ru: "комикс" },
  { id: 653, word: "roman", uk: "роман", ru: "роман" },
  { id: 654, word: "pozornica", uk: "сцена", ru: "сцена" },
  { id: 655, word: "aparat za pritisak", uk: "апарат для тиску", ru: "тонометр" },
  { id: 656, word: "injekcija", uk: "ін’єкція", ru: "инъекция" },
  { id: 657, word: "zdravstvena knjižica", uk: "медична картка", ru: "медицинская карта" },
  { id: 658, word: "karton (med.)", uk: "мед. карта (картон)", ru: "мед. карта" },
  { id: 659, word: "terapija", uk: "терапія", ru: "терапия" },
  { id: 660, word: "programiranje", uk: "програмування", ru: "программирование" },
  { id: 661, word: "biblioteka (soft)", uk: "бібліотека (ПЗ)", ru: "библиотека (ПО)" },
  { id: 662, word: "okvir (framework)", uk: "фреймворк", ru: "фреймворк" },
  { id: 663, word: "baza podataka", uk: "база даних", ru: "база данных" },
  { id: 664, word: "tabela (BD)", uk: "таблиця (БД)", ru: "таблица (БД)" },
  { id: 665, word: "server", uk: "сервер", ru: "сервер" },
  { id: 666, word: "API", uk: "API", ru: "API" },
  { id: 667, word: "token", uk: "токен", ru: "токен" },
  { id: 668, word: "greška", uk: "помилка", ru: "ошибка" },
  { id: 669, word: "izuzetak", uk: "виняток", ru: "исключение" },
  { id: 670, word: "vesti", uk: "новини", ru: "новости" },
  { id: 671, word: "oglas", uk: "оголошення/реклама", ru: "объявление/реклама" },
  { id: 672, word: "plakat", uk: "плакат", ru: "плакат" },
  { id: 673, word: "brošura", uk: "брошура", ru: "брошюра" },
  { id: 674, word: "saopštenje", uk: "повідомлення (офіц.)", ru: "сообщение (офиц.)" },
  { id: 675, word: "intervju", uk: "інтерв’ю", ru: "интервью" },
  { id: 676, word: "venčanje", uk: "весілля", ru: "свадьба" },
  { id: 677, word: "veridba", uk: "заручини", ru: "помолвка" },
  { id: 678, word: "razvod", uk: "розлучення", ru: "развод" },
  { id: 679, word: "deca", uk: "діти", ru: "дети" },
  { id: 680, word: "beba", uk: "немовля", ru: "младенец" },
  { id: 681, word: "kolica (dit.)", uk: "візочок", ru: "коляска" },
  { id: 682, word: "pelena", uk: "підгузок", ru: "подгузник" },
  { id: 683, word: "opasnost", uk: "небезпека", ru: "опасность" },
  { id: 684, word: "kazna", uk: "штраф/покарання", ru: "штраф/наказание" },
  { id: 685, word: "prijava", uk: "заява/скарга", ru: "заявление/жалоба" },
  { id: 686, word: "dozvola boravka", uk: "дозвіл на проживання", ru: "вид на жительство" },
  { id: 687, word: "ugovor o radu", uk: "трудовий договір", ru: "трудовой договор" },
  { id: 688, word: "red (porяdok)", uk: "порядок", ru: "порядок" },
  { id: 689, word: "pravac", uk: "напрям/курс", ru: "направление" },
  { id: 690, word: "strana", uk: "сторона", ru: "сторона" },
  { id: 691, word: "kopija", uk: "копія", ru: "копия" },
  { id: 692, word: "januar", uk: "січень", ru: "январь" },
  { id: 693, word: "februar", uk: "лютий", ru: "февраль" },
  { id: 694, word: "mart", uk: "березень", ru: "март" },
  { id: 695, word: "april", uk: "квітень", ru: "апрель" },
  { id: 696, word: "maj", uk: "травень", ru: "май" },
  { id: 697, word: "jun", uk: "червень", ru: "июнь" },
  { id: 698, word: "jul", uk: "липень", ru: "июль" },
  { id: 699, word: "avgust", uk: "серпень", ru: "август" },
  { id: 700, word: "septembar", uk: "вересень", ru: "сентябрь" },
  { id: 701, word: "oktobar", uk: "жовтень", ru: "октябрь" },
  { id: 702, word: "novembar", uk: "листопад", ru: "ноябрь" },
  { id: 703, word: "decembar", uk: "грудень", ru: "декабрь" }
];

// === SR_ADVERBS ===
window.decks.sr_adverbs = [
  { id: 1, word: "sada", uk: "зараз", ru: "сейчас" },
  { id: 2, word: "samo", uk: "тільки", ru: "только" },
  { id: 3, word: "takođe", uk: "також", ru: "тоже" },
  { id: 4, word: "vrlo", uk: "дуже", ru: "очень" },
  { id: 5, word: "uvek", uk: "завжди", ru: "всегда" },
  { id: 6, word: "nikad", uk: "ніколи", ru: "никогда" },
  { id: 7, word: "ponekad", uk: "іноді", ru: "иногда" },
  { id: 8, word: "često", uk: "часто", ru: "часто" },
  { id: 9, word: "retko", uk: "рідко", ru: "редко" },
  { id: 10, word: "uskoro", uk: "незабаром", ru: "скоро" },
  { id: 11, word: "odmah", uk: "відразу", ru: "сразу" },
  { id: 12, word: "danas", uk: "сьогодні", ru: "сегодня" },
  { id: 13, word: "juče", uk: "вчора", ru: "вчера" },
  { id: 14, word: "sutra", uk: "завтра", ru: "завтра" },
  { id: 15, word: "prekosutra", uk: "післязавтра", ru: "послезавтра" },
  { id: 16, word: "prekjuče", uk: "позавчора", ru: "позавчера" },
  { id: 17, word: "ranije", uk: "раніше", ru: "раньше" },
  { id: 18, word: "kasnije", uk: "пізніше", ru: "позже" },
  { id: 19, word: "tada", uk: "тоді", ru: "тогда" },
  { id: 20, word: "iznenada", uk: "раптом", ru: "вдруг" },
  { id: 21, word: "napokon", uk: "нарешті", ru: "наконец" },
  { id: 22, word: "verovatno", uk: "ймовірно", ru: "вероятно" },
  { id: 23, word: "možda", uk: "можливо", ru: "может быть" },
  { id: 24, word: "sigurno", uk: "напевно", ru: "точно/наверняка" },
  { id: 25, word: "tačno", uk: "точно", ru: "точно" },
  { id: 26, word: "rado", uk: "охоче", ru: "охотно" },
  { id: 27, word: "radije", uk: "краще (волів би)", ru: "лучше (охотнее)" },
  { id: 28, word: "najradije", uk: "найбільше", ru: "больше всего" },
  { id: 29, word: "zajedno", uk: "разом", ru: "вместе" },
  { id: 30, word: "sami", uk: "самі/наодинці", ru: "в одиночку" },
  { id: 31, word: "ovde", uk: "тут", ru: "здесь" },
  { id: 32, word: "tamo", uk: "там", ru: "там" },
  { id: 33, word: "tu", uk: "тут/там", ru: "здесь/там" },
  { id: 34, word: "svuda", uk: "скрізь", ru: "везде" },
  { id: 35, word: "negde", uk: "десь", ru: "где-то" },
  { id: 36, word: "nigde", uk: "ніде", ru: "нигде" },
  { id: 37, word: "gore", uk: "вгору/нагорі", ru: "наверху" },
  { id: 38, word: "dole", uk: "вниз/внизу", ru: "внизу" },
  { id: 39, word: "unutra", uk: "всередині", ru: "внутри" },
  { id: 40, word: "levo", uk: "ліворуч", ru: "налево" },
  { id: 41, word: "desno", uk: "праворуч", ru: "направо" },
  { id: 42, word: "napred", uk: "вперед", ru: "вперёд" },
  { id: 43, word: "pozadi", uk: "позаду", ru: "сзади" },
  { id: 44, word: "dalje", uk: "далі", ru: "дальше" },
  { id: 45, word: "upravo", uk: "щойно/саме", ru: "только что/как раз" },
  { id: 46, word: "tako", uk: "так/таким чином", ru: "так/таким образом" },
  { id: 47, word: "drugačije", uk: "інакше", ru: "по-другому" },
  { id: 48, word: "isto", uk: "так само", ru: "так же" },
  { id: 49, word: "dovoljno", uk: "достатньо", ru: "достаточно" },
  { id: 50, word: "prilično", uk: "досить", ru: "довольно" },
  { id: 51, word: "potpuno", uk: "повністю", ru: "полностью" },
  { id: 52, word: "uopšte", uk: "взагалі", ru: "вообще" },
  { id: 53, word: "ponovo", uk: "знову", ru: "снова" },
  { id: 54, word: "zatim", uk: "потім", ru: "затем" },
  { id: 55, word: "onda", uk: "тоді/потім", ru: "тогда/потом" },
  { id: 56, word: "odande", uk: "звідти", ru: "оттуда" },
  { id: 57, word: "obično", uk: "зазвичай", ru: "обычно" },
  { id: 58, word: "uglavnom", uk: "переважно/здебільшого", ru: "в основном" },
  { id: 59, word: "svakako", uk: "обов’язково/будь-що-будь", ru: "во всяком случае" },
  { id: 60, word: "naravno", uk: "звичайно/звісно", ru: "конечно" }
];

// === SR_ADJECTIVES ===
window.decks.sr_adjectives = [
  { id: 1, word: "dobar", uk: "добрий", ru: "хороший" },
  { id: 2, word: "loš", uk: "поганий", ru: "плохой" },
  { id: 3, word: "veliki", uk: "великий", ru: "большой" },
  { id: 4, word: "mali", uk: "малий", ru: "маленький" },
  { id: 5, word: "lep", uk: "гарний", ru: "красивый" },
  { id: 6, word: "ružan", uk: "потворний", ru: "уродливый" },
  { id: 7, word: "nov", uk: "новий", ru: "новый" },
  { id: 8, word: "star", uk: "старий", ru: "старый" },
  { id: 9, word: "mlad", uk: "молодий", ru: "молодой" },
  { id: 10, word: "jednostavan", uk: "простий", ru: "простой" },
  { id: 11, word: "težak", uk: "важкий/складний", ru: "тяжёлый/сложный" },
  { id: 12, word: "lak", uk: "легкий", ru: "лёгкий" },
  { id: 13, word: "brz", uk: "швидкий", ru: "быстрый" },
  { id: 14, word: "spor", uk: "повільний", ru: "медленный" },
  { id: 15, word: "rani", uk: "ранній", ru: "ранний" },
  { id: 16, word: "kasni", uk: "пізній", ru: "поздний" },
  { id: 17, word: "vruć", uk: "гарячий", ru: "горячий" },
  { id: 18, word: "hladan", uk: "холодний", ru: "холодный" },
  { id: 19, word: "topao", uk: "теплий", ru: "тёплый" },
  { id: 20, word: "prijatan", uk: "приємний", ru: "приятный" },
  { id: 21, word: "ljubazan", uk: "люб’язний", ru: "вежливый" },
  { id: 22, word: "neljubazan", uk: "неввічливий", ru: "невежливый" },
  { id: 23, word: "srećan", uk: "щасливий", ru: "счастливый" },
  { id: 24, word: "tužan", uk: "сумний", ru: "грустный" },
  { id: 25, word: "tih", uk: "тихий", ru: "тихий" },
  { id: 26, word: "glasan", uk: "гучний", ru: "громкий" },
  { id: 27, word: "jak", uk: "сильний", ru: "сильный" },
  { id: 28, word: "slab", uk: "слабкий", ru: "слабый" },
  { id: 29, word: "zdrav", uk: "здоровий", ru: "здоровый" },
  { id: 30, word: "bolestan", uk: "хворий", ru: "больной" },
  { id: 31, word: "bogat", uk: "багатий", ru: "богатый" },
  { id: 32, word: "siromašan", uk: "бідний", ru: "бедный" },
  { id: 33, word: "skup", uk: "дорогий", ru: "дорогой" },
  { id: 34, word: "jeftin", uk: "дешевий", ru: "дешёвый" },
  { id: 35, word: "svetao", uk: "світлий", ru: "светлый" },
  { id: 36, word: "taman", uk: "темний", ru: "тёмный" },
  { id: 37, word: "blizak", uk: "близький", ru: "близкий" },
  { id: 38, word: "dalek", uk: "далекий", ru: "далёкий" },
  { id: 39, word: "tačan", uk: "точний", ru: "точный" },
  { id: 40, word: "pogrešan", uk: "неправильний", ru: "неправильный" },
  { id: 41, word: "poznat", uk: "відомий", ru: "известный" },
  { id: 42, word: "nepoznat", uk: "невідомий", ru: "неизвестный" },
  { id: 43, word: "slobodan", uk: "вільний", ru: "свободный" },
  { id: 44, word: "zauzet", uk: "зайнятий", ru: "занятый" },
  { id: 45, word: "otvoren", uk: "відкритий", ru: "открытый" },
  { id: 46, word: "zatvoren", uk: "закритий", ru: "закрытый" },
  { id: 47, word: "zanimljiv", uk: "цікавий", ru: "интересный" },
  { id: 48, word: "dosadan", uk: "нудний", ru: "скучный" },
  { id: 49, word: "važan", uk: "важливий", ru: "важный" },
  { id: 50, word: "beznačajan", uk: "неважливий", ru: "неважный" },
  { id: 51, word: "siguran", uk: "безпечний/надійний", ru: "надёжный/безопасный" },
  { id: 52, word: "nesiguran", uk: "небезпечний", ru: "ненадёжный/опасный" },
  { id: 53, word: "vredan", uk: "працьовитий/цінний", ru: "трудолюбивый/ценный" },
  { id: 54, word: "lenj", uk: "ледачий", ru: "ленивый" },
  { id: 55, word: "umoran", uk: "втомлений", ru: "уставший" },
  { id: 56, word: "budan", uk: "бадьорий", ru: "бодрый" },
  { id: 57, word: "visok", uk: "високий", ru: "высокий" },
  { id: 58, word: "nizak", uk: "низький", ru: "низкий" },
  { id: 59, word: "dubok", uk: "глибокий", ru: "глубокий" },
  { id: 60, word: "plitak", uk: "плаский", ru: "мелкий" },
  { id: 61, word: "gladan", uk: "голодний", ru: "голодный" },
  { id: 62, word: "žedan", uk: "спраглий", ru: "жаждущий" },
  { id: 63, word: "sit", uk: "ситий", ru: "сытый" },
  { id: 64, word: "kriv", uk: "винний", ru: "виновный" },
  { id: 65, word: "nevin", uk: "невинний", ru: "невиновный" },
  { id: 66, word: "koristan", uk: "корисний", ru: "полезный" },
  { id: 67, word: "beskoristan", uk: "марний", ru: "бесполезный" },
  { id: 68, word: "stvaran", uk: "справжній", ru: "реальный" },
  { id: 69, word: "čudan", uk: "дивний", ru: "странный" },
  { id: 70, word: "tipičan", uk: "типовий", ru: "типичный" },
  { id: 71, word: "službeni", uk: "офіційний", ru: "официальный" },
  { id: 72, word: "privatan", uk: "приватний", ru: "частный" },
  { id: 73, word: "pametan", uk: "розумний", ru: "умный" },
  { id: 74, word: "glup", uk: "дурний", ru: "глупый" },
  { id: 75, word: "kratak", uk: "короткий", ru: "короткий" },
  { id: 76, word: "dugačak", uk: "довгий", ru: "длинный" },
  { id: 77, word: "novčan", uk: "грошовий", ru: "денежный" },
  { id: 78, word: "radan", uk: "робочий/працьовитий", ru: "рабочий/трудолюбивый" },
  { id: 79, word: "besmislen", uk: "безглуздий", ru: "бессмысленный" }
];

// === SR_PREPOSITIONS ===
window.decks.sr_prepositions = [
  { id: 1, word: "u", uk: "в", ru: "в" },
  { id: 2, word: "na", uk: "на", ru: "на" },
  { id: 3, word: "sa", uk: "з, разом з", ru: "с, вместе с" },
  { id: 4, word: "bez", uk: "без", ru: "без" },
  { id: 5, word: "za", uk: "для/за", ru: "для/за" },
  { id: 6, word: "od", uk: "від", ru: "от" },
  { id: 7, word: "do", uk: "до", ru: "до" },
  { id: 8, word: "kod", uk: "у (в когось)", ru: "у, у кого-то" },
  { id: 9, word: "po", uk: "по", ru: "по" },
  { id: 10, word: "pri", uk: "при", ru: "при" },
  { id: 11, word: "prema", uk: "до/щодо", ru: "к/по отношению к" },
  { id: 12, word: "kroz", uk: "крізь", ru: "через" },
  { id: 13, word: "iz", uk: "з, із", ru: "из" },
  { id: 14, word: "ispred", uk: "перед", ru: "перед" },
  { id: 15, word: "iza", uk: "позаду", ru: "за (сзади)" },
  { id: 16, word: "iznad", uk: "над", ru: "над" },
  { id: 17, word: "ispod", uk: "під", ru: "под" },
  { id: 18, word: "između", uk: "між", ru: "между" },
  { id: 19, word: "tokom", uk: "протягом", ru: "в течение" },
  { id: 20, word: "zbog", uk: "через/заради", ru: "из-за" },
  { id: 21, word: "uprkos", uk: "незважаючи на", ru: "несмотря на" },
  { id: 22, word: "oko", uk: "біля/навколо", ru: "около/вокруг" },
  { id: 23, word: "pored", uk: "поруч", ru: "рядом с" },
  { id: 24, word: "preko", uk: "через/поверх", ru: "через/поверх" },
  { id: 25, word: "među", uk: "серед", ru: "среди" },
  { id: 26, word: "van", uk: "поза", ru: "вне" },
  { id: 27, word: "unutar", uk: "всередині", ru: "внутри" },
  { id: 28, word: "napolju", uk: "зовні", ru: "снаружи" },
  { id: 29, word: "pre", uk: "перед (час)", ru: "до (по времени)" },
  { id: 30, word: "posle", uk: "після", ru: "после" },
  { id: 31, word: "za vreme", uk: "під час", ru: "во время" },
  { id: 32, word: "usled", uk: "внаслідок", ru: "вследствие" },
  { id: 33, word: "radi", uk: "задля", ru: "ради" },
  { id: 34, word: "nasuprot", uk: "навпроти", ru: "напротив" },
  { id: 35, word: "putem", uk: "шляхом/через", ru: "путём/через" },
  { id: 36, word: "o", uk: "про", ru: "о" },
  { id: 37, word: "prema gore", uk: "вгору", ru: "вверх" },
  { id: 38, word: "prema dole", uk: "вниз", ru: "вниз" },
  { id: 39, word: "prema unutra", uk: "всередину", ru: "внутрь" },
  { id: 40, word: "prema napolje", uk: "назовні", ru: "наружу" }
];

// === SR_PRONOUNS ===
window.decks.sr_pronouns = [
  { id: 1, word: "ja", uk: "я", ru: "я" },
  { id: 2, word: "ti", uk: "ти", ru: "ты" },
  { id: 3, word: "on", uk: "він", ru: "он" },
  { id: 4, word: "ona", uk: "вона", ru: "она" },
  { id: 5, word: "ono", uk: "воно", ru: "оно" },
  { id: 6, word: "mi", uk: "ми", ru: "мы" },
  { id: 7, word: "vi", uk: "ви", ru: "вы" },
  { id: 8, word: "oni", uk: "вони", ru: "они" },
  { id: 9, word: "moj", uk: "мій", ru: "мой" },
  { id: 10, word: "tvoj", uk: "твій", ru: "твой" },
  { id: 11, word: "njegov", uk: "його", ru: "его" },
  { id: 12, word: "njen", uk: "її", ru: "её" },
  { id: 13, word: "naš", uk: "наш", ru: "наш" },
  { id: 14, word: "vaš", uk: "ваш", ru: "ваш" },
  { id: 15, word: "njihov", uk: "їхній", ru: "их" },
  { id: 16, word: "ovaj", uk: "цей", ru: "этот" },
  { id: 17, word: "taj", uk: "той (ближ.)", ru: "тот (ближ.)" },
  { id: 18, word: "onaj", uk: "он той (дал.)", ru: "вон тот (дал.)" },
  { id: 19, word: "koji", uk: "який", ru: "какой/который" },
  { id: 20, word: "ko", uk: "хто", ru: "кто" },
  { id: 21, word: "šta", uk: "що", ru: "что" },
  { id: 22, word: "neko", uk: "хтось", ru: "кто-то" },
  { id: 23, word: "niko", uk: "ніхто", ru: "никто" },
  { id: 24, word: "nešto", uk: "щось", ru: "что-то" },
  { id: 25, word: "ništa", uk: "нічого", ru: "ничего" },
  { id: 26, word: "ga", uk: "його (його/його го)", ru: "его" },
  { id: 27, word: "je", uk: "її", ru: "её" },
  { id: 28, word: "ih", uk: "їх", ru: "их" },
  { id: 29, word: "mu", uk: "йому", ru: "ему" },
  { id: 30, word: "joj", uk: "їй", ru: "ей" },
  { id: 31, word: "nam", uk: "нам", ru: "нам" },
  { id: 32, word: "vam", uk: "вам", ru: "вам" },
  { id: 33, word: "im", uk: "їм", ru: "им" },
  { id: 34, word: "me", uk: "мене (кл.)", ru: "меня (кл.)" },
  { id: 35, word: "te", uk: "тебе (кл.)", ru: "тебя (кл.)" }
];

// === SR_NUMBERS ===
window.decks.sr_numbers = [
  { id: 1, word: "jedan", uk: "один", ru: "один" },
  { id: 2, word: "dva", uk: "два", ru: "два" },
  { id: 3, word: "tri", uk: "три", ru: "три" },
  { id: 4, word: "četiri", uk: "чотири", ru: "четыре" },
  { id: 5, word: "pet", uk: "п’ять", ru: "пять" },
  { id: 6, word: "šest", uk: "шість", ru: "шесть" },
  { id: 7, word: "sedam", uk: "сім", ru: "семь" },
  { id: 8, word: "osam", uk: "вісім", ru: "восемь" },
  { id: 9, word: "devet", uk: "дев’ять", ru: "девять" },
  { id: 10, word: "deset", uk: "десять", ru: "десять" },
  { id: 11, word: "jedanaest", uk: "одинадцять", ru: "одиннадцать" },
  { id: 12, word: "dvanaest", uk: "дванадцять", ru: "двенадцать" },
  { id: 13, word: "trinaest", uk: "тринадцять", ru: "тринадцать" },
  { id: 14, word: "četrnaest", uk: "чотирнадцять", ru: "четырнадцать" },
  { id: 15, word: "petnaest", uk: "п’ятнадцять", ru: "пятнадцать" },
  { id: 16, word: "šesnaest", uk: "шістнадцять", ru: "шестнадцать" },
  { id: 17, word: "sedamnaest", uk: "сімнадцять", ru: "семнадцать" },
  { id: 18, word: "osamnaest", uk: "вісімнадцять", ru: "восемнадцать" },
  { id: 19, word: "devetnaest", uk: "дев’ятнадцять", ru: "девятнадцать" },
  { id: 20, word: "dvadeset", uk: "двадцять", ru: "двадцать" },
  { id: 21, word: "trideset", uk: "тридцять", ru: "тридцать" },
  { id: 22, word: "četrdeset", uk: "сорок", ru: "сорок" },
  { id: 23, word: "pedeset", uk: "п’ятдесят", ru: "пятьдесят" },
  { id: 24, word: "šezdeset", uk: "шістдесят", ru: "шестьдесят" },
  { id: 25, word: "sedamdeset", uk: "сімдесят", ru: "семьдесят" },
  { id: 26, word: "osamdeset", uk: "вісімдесят", ru: "восемьдесят" },
  { id: 27, word: "devedeset", uk: "дев’яносто", ru: "девяносто" },
  { id: 28, word: "sto", uk: "сто", ru: "сто" },
  { id: 29, word: "hiljadu", uk: "тисяча", ru: "тысяча" },
  { id: 30, word: "prvi", uk: "перший", ru: "первый" },
  { id: 31, word: "drugi", uk: "другий", ru: "второй" },
  { id: 32, word: "treći", uk: "третій", ru: "третий" },
  { id: 33, word: "četvrti", uk: "четвертий", ru: "четвёртый" },
  { id: 34, word: "peti", uk: "п’ятий", ru: "пятый" },
  { id: 35, word: "poslednji", uk: "останній", ru: "последний" }
];

// === SR_CONJUNCTIONS ===
window.decks.sr_conjunctions = [
  { id: 1, word: "i", uk: "і", ru: "и" },
  { id: 2, word: "ili", uk: "або", ru: "или" },
  { id: 3, word: "ali", uk: "але", ru: "но" },
  { id: 4, word: "jer", uk: "бо/тому що", ru: "ибо/потому что" },
  { id: 5, word: "zato što", uk: "тому що", ru: "потому что" },
  { id: 6, word: "da", uk: "щоб/що", ru: "чтобы/что" },
  { id: 7, word: "ako", uk: "якщо", ru: "если" },
  { id: 8, word: "iako", uk: "хоча", ru: "хотя" },
  { id: 9, word: "dok", uk: "поки/в той час як", ru: "пока/в то время как" },
  { id: 10, word: "pre nego što", uk: "перш ніж", ru: "прежде чем" },
  { id: 11, word: "posle što", uk: "після того як", ru: "после того как" },
  { id: 12, word: "čim", uk: "щойно/як тільки", ru: "как только" },
  { id: 13, word: "da bi", uk: "щоб", ru: "чтобы" },
  { id: 14, word: "dakle", uk: "отже", ru: "итак" },
  { id: 15, word: "zato", uk: "тому/тому-то", ru: "поэтому" },
  { id: 16, word: "nego", uk: "а (вместо)", ru: "а (вместо этого)" },
  { id: 17, word: "međutim", uk: "проте", ru: "однако" },
  { id: 18, word: "što više", uk: "чим більше", ru: "чем больше" },
  { id: 19, word: "kao i", uk: "а також", ru: "а также" },
  { id: 20, word: "pa", uk: "і/та/так", ru: "и/да/так" }
];

// === SR_PARTICLES ===
window.decks.sr_particles = [
  { id: 1, word: "baš", uk: "саме/прямо", ru: "прямо/именно" },
  { id: 2, word: "već", uk: "вже/та й", ru: "уже/да уж" },
  { id: 3, word: "valjda", uk: "мабуть", ru: "наверное" },
  { id: 4, word: "eto", uk: "ось/от", ru: "вот" },
  { id: 5, word: "ma", uk: "та/та ну", ru: "да/да ну" },
  { id: 6, word: "tek", uk: "лише/тільки", ru: "лишь/только" },
  { id: 7, word: "još", uk: "ще", ru: "ещё" },
  { id: 8, word: "evo", uk: "ось", ru: "вот (же)" },
  { id: 9, word: "eno", uk: "он там", ru: "вон там" }
];

