/* ==========================================================
 * Project: MOYAMOVA
 * File: deck.fr.js
 * Purpose: Логика приложения (JS)
 * Version: 1.0
 * Last modified: 2025-10-19
*/

window.decks = window.decks || {};

window.decks.fr_verbs = [
  { id: 1, word: "être", uk: "бути", ru: "быть" },
  { id: 2, word: "avoir", uk: "мати", ru: "иметь" },
  { id: 3, word: "faire", uk: "робити", ru: "делать" },
  { id: 4, word: "dire", uk: "казати", ru: "сказать" },
  { id: 5, word: "aller", uk: "йти/їхати", ru: "идти/ехать" },
  { id: 6, word: "voir", uk: "бачити", ru: "видеть" },
  { id: 7, word: "savoir", uk: "знати", ru: "знать" },

  { id: 9, word: "vouloir", uk: "хотіти", ru: "хотеть" },
  { id: 10, word: "venir", uk: "приходити", ru: "приходить" },
  { id: 11, word: "prendre", uk: "брати", ru: "брать" },
  { id: 12, word: "mettre", uk: "класти", ru: "класть" },
  { id: 13, word: "donner", uk: "давати", ru: "давать" },
  { id: 14, word: "parler", uk: "говорити", ru: "говорить" },
  { id: 15, word: "trouver", uk: "знаходити", ru: "находить" },
  { id: 16, word: "comprendre", uk: "розуміти", ru: "понимать" },
  { id: 17, word: "aimer", uk: "любити", ru: "любить" },
  { id: 18, word: "penser", uk: "думати", ru: "думать" },
  { id: 19, word: "laisser", uk: "дозволяти", ru: "позволять" },
  { id: 20, word: "passer", uk: "витрачати/проводити", ru: "тратить/проводить" },
  { id: 21, word: "regarder", uk: "дивитися", ru: "смотреть" },
  { id: 22, word: "croire", uk: "вірити", ru: "верить" },
  { id: 23, word: "demander", uk: "питати/просити", ru: "спрашивать/просить" },

  { id: 27, word: "partir", uk: "йти/залишати", ru: "уходить/покидать" },

  { id: 29, word: "rester", uk: "залишатися", ru: "оставаться" },
  { id: 30, word: "rendre", uk: "повертати(ся)", ru: "возвращать(ся)" },
  { id: 31, word: "porter", uk: "нести", ru: "нести" },
  { id: 32, word: "travailler", uk: "працювати", ru: "работать" },
  { id: 33, word: "utiliser", uk: "використовувати", ru: "использовать" },
  { id: 34, word: "essayer", uk: "пробувати", ru: "пытаться" },
  { id: 35, word: "jouer", uk: "грати", ru: "играть" },
  { id: 36, word: "courir", uk: "бігти/керувати", ru: "бежать/управлять" },
  { id: 37, word: "bouger", uk: "рухатися", ru: "двигаться" },
  { id: 38, word: "vivre", uk: "жити", ru: "жить" },
  { id: 39, word: "ouvrir", uk: "відкривати", ru: "открывать" },

  { id: 41, word: "envoyer", uk: "надсилати", ru: "посылать" },
  { id: 42, word: "recevoir", uk: "отримувати", ru: "получать" },
  { id: 43, word: "attendre", uk: "чекати", ru: "ждать" },
  { id: 44, word: "conduire", uk: "водити", ru: "водить" },
  { id: 45, word: "manger", uk: "їсти", ru: "есть" },
  { id: 46, word: "boire", uk: "пити", ru: "пить" },
  { id: 47, word: "dormir", uk: "спати", ru: "спать" },
  { id: 48, word: "apprendre", uk: "вчитися", ru: "учиться" },
  { id: 49, word: "enseigner", uk: "викладати", ru: "преподавать" },
  { id: 50, word: "voyager", uk: "подорожувати", ru: "путешествовать" },
  { id: 51, word: "choisir", uk: "обирати", ru: "выбирать" },
  { id: 52, word: "espérer", uk: "сподіватися", ru: "надеяться" },
  { id: 53, word: "aider", uk: "допомагати", ru: "помогать" },
  { id: 54, word: "expliquer", uk: "пояснювати", ru: "объяснять" },
  { id: 55, word: "acheter", uk: "купувати", ru: "покупать" },

  { id: 57, word: "apporter", uk: "приносити", ru: "приносить" },
  { id: 58, word: "atteindre", uk: "досягати", ru: "достигать" },

  { id: 61, word: "changer", uk: "міняти", ru: "менять" },

  { id: 63, word: "construire", uk: "будувати", ru: "строить" },
  { id: 64, word: "continuer", uk: "продовжувати", ru: "продолжать" },
  { id: 65, word: "cuisiner", uk: "готувати", ru: "готовить" },

  { id: 70, word: "lire", uk: "читати", ru: "читать" },
  { id: 71, word: "montrer", uk: "показувати", ru: "показывать" },
  { id: 72, word: "nettoyer", uk: "чистити/прибирати", ru: "чистить/убирать" },
  { id: 73, word: "offrir", uk: "пропонувати", ru: "предлагать" },

  { id: 75, word: "payer", uk: "платити", ru: "платить" },

  { id: 79, word: "raconter", uk: "розповідати", ru: "рассказывать" },

  { id: 84, word: "retourner", uk: "повертати(ся)", ru: "возвращать(ся)" },

  { id: 88, word: "suivre", uk: "слідувати", ru: "следовать" },

  { id: 92, word: "tomber", uk: "падати", ru: "падать" },
  { id: 93, word: "tourner", uk: "повертати/ставати", ru: "поворачивать/становиться" },

  { id: 95, word: "utiliser", uk: "використовувати", ru: "использовать" },

  { id: 101, word: "adapter", uk: "адаптуватися", ru: "адаптироваться" },

  { id: 113, word: "clarifier", uk: "уточнювати", ru: "уточнять" },
  { id: 114, word: "coordonner", uk: "координувати", ru: "координировать" },
  { id: 115, word: "déployer", uk: "розгортати/впроваджувати", ru: "развёртывать/внедрять" },

  { id: 123, word: "entretenir", uk: "підтримувати/обслуговувати", ru: "поддерживать/обслуживать" },

  { id: 126, word: "garantir", uk: "гарантувати", ru: "гарантировать" },

  { id: 129, word: "négocier", uk: "вести переговори", ru: "вести переговоры" },

  { id: 131, word: "obtenir", uk: "отримувати", ru: "получать" },
  { id: 132, word: "opérer", uk: "працювати/керувати", ru: "работать/управлять" },
  { id: 133, word: "organiser", uk: "організовувати", ru: "организовывать" },

  { id: 142, word: "sécuriser", uk: "захищати", ru: "защищать" },

  { id: 145, word: "surveiller", uk: "моніторити/слідкувати", ru: "мониторить/следить" },

  { id: 149, word: "valider", uk: "валідовати/підтверджувати", ru: "валидировать/подтверждать" }
];

window.decks.fr_nouns = [
  { id: 1, word: "temps", uk: "час", ru: "время" },
  { id: 2, word: "année", uk: "рік", ru: "год" },
  { id: 3, word: "gens", uk: "люди", ru: "люди" },
  { id: 4, word: "jour", uk: "день", ru: "день" },
  { id: 5, word: "homme", uk: "чоловік", ru: "мужчина" },
  { id: 6, word: "femme", uk: "жінка", ru: "женщина" },
  { id: 7, word: "enfant", uk: "дитина", ru: "ребёнок" },
  { id: 8, word: "vie", uk: "життя", ru: "жизнь" },
  { id: 9, word: "monde", uk: "світ", ru: "мир" },
  { id: 10, word: "école", uk: "школа", ru: "школа" },
  { id: 11, word: "étudiant", uk: "студент", ru: "студент" },
  { id: 12, word: "famille", uk: "сім’я", ru: "семья" },
  { id: 13, word: "ami", uk: "друг", ru: "друг" },
  { id: 14, word: "pays", uk: "країна", ru: "страна" },
  { id: 15, word: "ville", uk: "місто", ru: "город" },
  { id: 16, word: "entreprise", uk: "компанія", ru: "компания" },
  { id: 17, word: "системе", uk: "система", ru: "система" },
  { id: 18, word: "programme", uk: "програма", ru: "программа" },
  { id: 19, word: "question", uk: "питання", ru: "вопрос" },
  { id: 20, word: "travail", uk: "робота", ru: "работа" },
  { id: 21, word: "maison", uk: "дім", ru: "дом" },
  { id: 22, word: "pièce", uk: "кімната", ru: "комната" },
  { id: 23, word: "appartement", uk: "квартира", ru: "квартира" },
  { id: 24, word: "cuisine", uk: "кухня", ru: "кухня" },
  { id: 25, word: "chambre", uk: "спальня", ru: "спальня" },
  { id: 26, word: "salle de bains", uk: "ванна/туалет", ru: "ванная/туалет" },
  { id: 27, word: "table", uk: "стіл", ru: "стол" },
  { id: 28, word: "chaise", uk: "стілець", ru: "стул" },
  { id: 29, word: "fenêtre", uk: "вікно", ru: "окно" },
  { id: 30, word: "porte", uk: "двері", ru: "дверь" },

  { id: 34, word: "rue", uk: "вулиця", ru: "улица" },
  { id: 35, word: "route", uk: "дорога", ru: "дорога" },
  { id: 36, word: "voiture", uk: "авто", ru: "машина" },
  { id: 37, word: "bus", uk: "автобус", ru: "автобус" },
  { id: 38, word: "train", uk: "поїзд", ru: "поезд" },
  { id: 39, word: "gare", uk: "станція", ru: "станция" },
  { id: 40, word: "aéroport", uk: "аеропорт", ru: "аэропорт" },
  { id: 41, word: "billet", uk: "квиток", ru: "билет" },
  { id: 42, word: "prix", uk: "ціна", ru: "цена" },
  { id: 43, word: "marché", uk: "ринок", ru: "рынок" },
  { id: 44, word: "magasin", uk: "магазин", ru: "магазин" },
  { id: 45, word: "restaurant", uk: "ресторан", ru: "ресторан" },
  { id: 46, word: "café", uk: "кава", ru: "кофе" },
  { id: 47, word: "bar", uk: "бар", ru: "бар" },
  { id: 48, word: "parc", uk: "парк", ru: "парк" },
  { id: 49, word: "rivière", uk: "річка", ru: "река" },
  { id: 50, word: "lac", uk: "озеро", ru: "озеро" },
  { id: 51, word: "mer", uk: "море", ru: "море" },
  { id: 52, word: "océan", uk: "океан", ru: "океан" },
  { id: 53, word: "montagne", uk: "гора", ru: "гора" },
  { id: 54, word: "forêt", uk: "ліс", ru: "лес" },
  { id: 55, word: "champ", uk: "поле", ru: "поле" },
  { id: 56, word: "désert", uk: "пустеля", ru: "пустыня" },
  { id: 57, word: "arbre", uk: "дерево", ru: "дерево" },
  { id: 58, word: "fleur", uk: "квітка", ru: "цветок" },
  { id: 59, word: "herbe", uk: "трава", ru: "трава" },
  { id: 60, word: "feuille", uk: "листок", ru: "лист" },
  { id: 61, word: "racine", uk: "корінь", ru: "корень" },
  { id: 62, word: "météo", uk: "погода", ru: "погода" },
  { id: 63, word: "pluie", uk: "дощ", ru: "дождь" },
  { id: 64, word: "neige", uk: "сніг", ru: "снег" },
  { id: 65, word: "soleil", uk: "сонце", ru: "солнце" },
  { id: 66, word: "vent", uk: "вітер", ru: "ветер" },
  { id: 67, word: "nuage", uk: "хмара", ru: "облако" },
  { id: 68, word: "tempête", uk: "буря", ru: "шторм" },
  { id: 69, word: "éclair", uk: "блискавка", ru: "молния" },
  { id: 70, word: "brouillard", uk: "туман", ru: "туман" },
  { id: 71, word: "glace", uk: "морозиво", ru: "мороженое" },
  { id: 72, word: "givre", uk: "іній", ru: "иней" },
  { id: 73, word: "téléphone", uk: "телефон", ru: "телефон" },
  { id: 74, word: "ordinateur", uk: "комп’ютер", ru: "компьютер" },
  { id: 75, word: "internet", uk: "інтернет", ru: "интернет" },
  { id: 76, word: "email", uk: "емейл", ru: "эмейл" },
  { id: 77, word: "mot de passe", uk: "пароль", ru: "пароль" },
  { id: 78, word: "compte", uk: "акаунт", ru: "аккаунт" },
  { id: 79, word: "profil", uk: "профіль", ru: "профиль" },
  { id: 80, word: "photo", uk: "фото", ru: "фото" },
  { id: 81, word: "musique", uk: "музика", ru: "музыка" },
  { id: 82, word: "vidéo", uk: "відео", ru: "видео" },
  { id: 83, word: "film", uk: "фільм", ru: "фильм" },
  { id: 84, word: "livre", uk: "книга", ru: "книга" },
  { id: 85, word: "page", uk: "сторінка", ru: "страница" },
  { id: 86, word: "lettre", uk: "лист", ru: "письмо" },
  { id: 87, word: "document", uk: "документ", ru: "документ" },
  { id: 88, word: "fichier", uk: "файл", ru: "файл" },
  { id: 89, word: "dossier", uk: "папка", ru: "папка" },
  { id: 90, word: "imprimante", uk: "принтер", ru: "принтер" },
  { id: 91, word: "papier", uk: "папір", ru: "бумага" },
  { id: 92, word: "stylo", uk: "ручка", ru: "ручка" },
  { id: 93, word: "crayon", uk: "олівець", ru: "карандаш" },
  { id: 94, word: "cahier", uk: "зошит", ru: "тетрадь" },
  { id: 95, word: "calendrier", uk: "календар", ru: "календарь" },
  { id: 96, word: "horloge", uk: "годинник", ru: "часы" },
  { id: 97, word: "montre", uk: "годинник (нар.)", ru: "часы (наручные)" },
  { id: 98, word: "sac", uk: "сумка", ru: "сумка" },
  { id: 99, word: "portefeuille", uk: "гаманець", ru: "кошелёк" },
  { id: 100, word: "clé", uk: "ключ", ru: "ключ" },
  { id: 101, word: "passeport", uk: "паспорт", ru: "паспорт" },
  { id: 102, word: "visa", uk: "віза", ru: "виза" },
  { id: 103, word: "bagage", uk: "багаж", ru: "багаж" },
  { id: 104, word: "valise", uk: "валіза", ru: "чемодан" },
  { id: 105, word: "sac à dos", uk: "рюкзак", ru: "рюкзак" },
  { id: 106, word: "carte", uk: "карта", ru: "карта" },
  { id: 107, word: "plan", uk: "план", ru: "план" },
  { id: 108, word: "idée", uk: "ідея", ru: "идея" },
  { id: 109, word: "problème", uk: "проблема", ru: "проблема" },
  { id: 110, word: "solution", uk: "рішення", ru: "решение" },
  { id: 111, word: "choix", uk: "вибір", ru: "выбор" },

  { id: 113, word: "changement", uk: "зміна", ru: "изменение" },
  { id: 114, word: "but", uk: "мета", ru: "цель" },
  { id: 115, word: "raison", uk: "причина", ru: "причина" },
  { id: 116, word: "résultat", uk: "результат", ru: "результат" },
  { id: 117, word: "effet", uk: "ефект", ru: "эффект" },

  { id: 120, word: "endroit", uk: "місце", ru: "место" },
  { id: 121, word: "zone", uk: "територія", ru: "территория" },
  { id: 122, word: "région", uk: "регіон", ru: "регион" },
  { id: 123, word: "capitale", uk: "столиця", ru: "столица" },
  { id: 124, word: "centre", uk: "центр", ru: "центр" },
  { id: 125, word: "place", uk: "площа", ru: "площадь" },
  { id: 126, word: "pont", uk: "міст", ru: "мост" },
  { id: 127, word: "hôpital", uk: "лікарня", ru: "больница" },
  { id: 128, word: "clinique", uk: "клініка", ru: "клиника" },
  { id: 129, word: "pharmacie", uk: "аптека", ru: "аптека" },
  { id: 130, word: "médecin", uk: "лікар", ru: "врач" },
  { id: 131, word: "infirmière", uk: "медсестра", ru: "медсестра" },
  { id: 132, word: "médicament", uk: "ліки", ru: "лекарство" },
  { id: 133, word: "pilule", uk: "таблетка", ru: "таблетка" },
  { id: 134, word: "bandage", uk: "бинт", ru: "бинт" },
  { id: 135, word: "blessure", uk: "травма", ru: "травма" },
  { id: 136, word: "fièvre", uk: "лихоманка/температура", ru: "жар/температура" },
  { id: 137, word: "toux", uk: "кашель", ru: "кашель" },
  { id: 138, word: "mal de tête", uk: "головний біль", ru: "головная боль" },
  { id: 139, word: "mal de dents", uk: "зубний біль", ru: "зубная боль" },
  { id: 140, word: "grippe", uk: "грип", ru: "грипп" },
  { id: 141, word: "rhume", uk: "застуда", ru: "простуда" },
  { id: 142, word: "santé", uk: "здоров’я", ru: "здоровье" },
  { id: 143, word: "corps", uk: "тіло", ru: "тело" },
  { id: 144, word: "tête", uk: "голова", ru: "голова" },
  { id: 145, word: "visage", uk: "обличчя", ru: "лицо" },
  { id: 146, word: "main", uk: "рука", ru: "рука" },
  { id: 147, word: "bras", uk: "рука (від плеча)", ru: "рука" },
  { id: 148, word: "jambe", uk: "нога", ru: "нога" },
  { id: 149, word: "pied", uk: "pied", ru: "pied" },
  { id: 150, word: "dos", uk: "спина", ru: "спина" },
  { id: 151, word: "coeur", uk: "серце", ru: "сердце" },
  { id: 152, word: "sang", uk: "кров", ru: "кровь" },
  { id: 153, word: "peau", uk: "шкіра", ru: "кожа" },
  { id: 154, word: "cheveux", uk: "волосся", ru: "волосы" },
  { id: 155, word: "oeil", uk: "око", ru: "глаз" },
  { id: 156, word: "oreille", uk: "вухо", ru: "ухо" },
  { id: 157, word: "nez", uk: "ніс", ru: "нос" },
  { id: 158, word: "bouche", uk: "рот", ru: "рот" },
  { id: 159, word: "dent", uk: "зуб", ru: "зуб" },
  { id: 160, word: "langue", uk: "мова", ru: "язык" },
  { id: 161, word: "mot", uk: "слово", ru: "слово" },
  { id: 162, word: "phrase", uk: "речення", ru: "предложение" },
  { id: 163, word: "texte", uk: "текст", ru: "текст" },
  { id: 164, word: "leçon", uk: "урок", ru: "урок" },
  { id: 165, word: "classe", uk: "клас", ru: "класс" },
  { id: 166, word: "professeur", uk: "вчитель", ru: "учитель" },
  { id: 167, word: "élève", uk: "студент", ru: "студент" },
  { id: 168, word: "examen", uk: "іспит", ru: "экзамен" },
  { id: 169, word: "test", uk: "тест", ru: "тест" },
  { id: 170, word: "note", uk: "бал", ru: "балл" },
  { id: 171, word: "matière", uk: "предмет", ru: "предмет" },
  { id: 172, word: "science", uk: "наука", ru: "наука" },
  { id: 173, word: "histoire", uk: "історія", ru: "история" },
  { id: 174, word: "art", uk: "мистецтво", ru: "искусство" },
  { id: 175, word: "musique", uk: "музика", ru: "музыка" },
  { id: 176, word: "sport", uk: "спорт", ru: "спорт" },
  { id: 177, word: "jeu", uk: "гра", ru: "игра" },
  { id: 178, word: "match", uk: "матч", ru: "матч" },
  { id: 179, word: "équipe", uk: "команда", ru: "команда" },
  { id: 180, word: "ballon", uk: "м’яч", ru: "мяч" },
  { id: 181, word: "gardien", uk: "gardien", ru: "gardien" },
  { id: 182, word: "entraîneur", uk: "тренер", ru: "тренер" },
  { id: 183, word: "joueur", uk: "гравець", ru: "игрок" },
  { id: 184, word: "règle", uk: "правило", ru: "правило" },
  { id: 185, word: "loi", uk: "закон", ru: "закон" },
  { id: 186, word: "droit", uk: "право", ru: "право" },
  { id: 187, word: "devoir", uk: "обов’язок", ru: "обязанность" },
  { id: 188, word: "police", uk: "поліція", ru: "полиция" },
  { id: 189, word: "tribunal", uk: "суд", ru: "суд" },
  { id: 190, word: "juge", uk: "суддя", ru: "судья" },
  { id: 191, word: "avocat", uk: "адвокат", ru: "адвокат" },
  { id: 192, word: "banque", uk: "банк", ru: "банк" },
  { id: 193, word: "argent", uk: "гроші", ru: "деньги" },
  { id: 194, word: "espèces", uk: "готівка", ru: "наличные" },
  { id: 195, word: "carte (bancaire)", uk: "картка", ru: "карта" },
  { id: 196, word: "crédit", uk: "кредит", ru: "кредит" },
  { id: 197, word: "dette", uk: "борг", ru: "долг" },
  { id: 198, word: "prêt", uk: "позика/кредит", ru: "заём/кредит" },
  { id: 199, word: "intérêt", uk: "відсоток/інтерес", ru: "процент/интерес" },
  { id: 200, word: "impôt", uk: "податок", ru: "налог" },
  { id: 201, word: "budget", uk: "бюджет", ru: "бюджет" },
  { id: 202, word: "bénéfice", uk: "прибуток", ru: "прибыль" },
  { id: 203, word: "perte", uk: "збиток", ru: "убыток" },
  { id: 204, word: "valeur", uk: "цінність", ru: "ценность" },
  { id: 205, word: "frais", uk: "комісія/збір", ru: "комиссия/сбор" },
  { id: 206, word: "salaire", uk: "зарплата", ru: "зарплата" },
  { id: 207, word: "facture", uk: "рахунок", ru: "счёт" },
  { id: 208, word: "paiement", uk: "платіж", ru: "платёж" },
  { id: 209, word: "dépense", uk: "витрата", ru: "расход" },
  { id: 210, word: "commerce", uk: "торгівля", ru: "торговля" },
  { id: 211, word: "économie", uk: "економіка", ru: "экономика" },
  { id: 212, word: "tendance", uk: "тенденція", ru: "тренд" },
  { id: 213, word: "emploi", uk: "робота/посада", ru: "работа/должность" },
  { id: 214, word: "carrière", uk: "кар’єра", ru: "карьера" },
  { id: 215, word: "profession", uk: "професія", ru: "профессия" },
  { id: 216, word: "bureau", uk: "офіс", ru: "офис" },
  { id: 217, word: "entreprise", uk: "компанія", ru: "компания" },
  { id: 218, word: "responsable", uk: "менеджер", ru: "менеджер" },
  { id: 219, word: "patron", uk: "шеф/керівник", ru: "шеф/руководитель" },
  { id: 220, word: "employé", uk: "співробітник", ru: "сотрудник" },
  { id: 221, word: "collègue", uk: "колега", ru: "коллега" },
  { id: 222, word: "client", uk: "клієнт", ru: "клиент" },

  { id: 224, word: "assistance", uk: "підтримка", ru: "поддержка" },
  { id: 225, word: "service", uk: "послуга/сервіс", ru: "услуга/сервис" },
  { id: 226, word: "entrepôt", uk: "склад", ru: "склад" },
  { id: 227, word: "usine", uk: "фабрика/завод", ru: "фабрика/завод" },
  { id: 228, word: "machine", uk: "верстат/машина", ru: "станок/машина" },
  { id: 229, word: "outil", uk: "інструмент", ru: "инструмент" },
  { id: 230, word: "appareil", uk: "пристрій", ru: "устройство" },
  { id: 231, word: "bouton", uk: "кнопка", ru: "кнопка" },
  { id: 232, word: "écran", uk: "екран", ru: "экран" },
  { id: 233, word: "clavier", uk: "клавіатура", ru: "клавиатура" },
  { id: 234, word: "souris", uk: "миша", ru: "мышь" },
  { id: 235, word: "câble", uk: "кабель", ru: "кабель" },
  { id: 236, word: "batterie", uk: "батарея", ru: "батарея" },
  { id: 237, word: "chargeur", uk: "зарядний пристрій", ru: "зарядное устройство" },
  { id: 238, word: "réseau", uk: "мережа", ru: "сеть" },
  { id: 239, word: "serveur", uk: "сервер", ru: "сервер" },

  { id: 241, word: "mise à jour", uk: "оновлення", ru: "обновление" },
  { id: 242, word: "fonction", uk: "функція", ru: "функция" },
  { id: 243, word: "bogue", uk: "помилка/баг", ru: "ошибка/баг" },
  { id: 244, word: "sauvegarde", uk: "резервна копія", ru: "резервная копия" },
  { id: 245, word: "confidentialité", uk: "конфіденційність", ru: "конфиденциальность" },
  { id: 246, word: "sécurité", uk: "безпека", ru: "безопасность" },
  { id: 247, word: "accès", uk: "доступ", ru: "доступ" },
  { id: 248, word: "paramètre", uk: "налаштування", ru: "настройка" },
  { id: 249, word: "option", uk: "опція", ru: "опция" },
  { id: 250, word: "notification", uk: "сповіщення", ru: "уведомление" },
  { id: 251, word: "message", uk: "повідомлення", ru: "сообщение" },
  { id: 252, word: "discussion", uk: "чат", ru: "чат" },
  { id: 253, word: "appel", uk: "дзвінок", ru: "звонок" },
  { id: 254, word: "réunion", uk: "зустріч/нарада", ru: "встреча/совещание" },
  { id: 255, word: "échéance", uk: "строк/дедлайн", ru: "срок/дедлайн" },
  { id: 256, word: "tâche", uk: "завдання", ru: "задача" },
  { id: 257, word: "projet", uk: "проєкт", ru: "проект" },
  { id: 258, word: "rapport", uk: "звіт", ru: "отчёт" },
  { id: 259, word: "contrat", uk: "контракт", ru: "контракт" },
  { id: 260, word: "accord", uk: "угода", ru: "соглашение" },
  { id: 261, word: "vacances", uk: "відпустка", ru: "отпуск" },
  { id: 262, word: "week-end", uk: "вихідні", ru: "выходные" },
  { id: 263, word: "matin", uk: "ранок", ru: "утро" },
  { id: 264, word: "après-midi", uk: "день", ru: "день" },
  { id: 265, word: "soir", uk: "вечір", ru: "вечер" },
  { id: 266, word: "nuit", uk: "ніч", ru: "ночь" },
  { id: 267, word: "hier", uk: "вчора", ru: "вчера" },
  { id: 268, word: "aujourd’hui", uk: "сьогодні", ru: "сегодня" },
  { id: 269, word: "demain", uk: "завтра", ru: "завтра" },
  { id: 270, word: "minute", uk: "хвилина", ru: "минута" },
  { id: 271, word: "heure", uk: "година", ru: "час" },
  { id: 272, word: "semaine", uk: "тиждень", ru: "неделя" },
  { id: 273, word: "mois", uk: "місяць", ru: "месяц" },
  { id: 274, word: "printemps", uk: "весна", ru: "весна" },
  { id: 275, word: "été", uk: "літо", ru: "лето" },
  { id: 276, word: "automne", uk: "осінь", ru: "осень" },
  { id: 277, word: "hiver", uk: "зима", ru: "зима" },
  { id: 278, word: "petit déjeuner", uk: "сніданок", ru: "завтрак" },
  { id: 279, word: "déjeuner", uk: "обід", ru: "обед" },
  { id: 280, word: "dîner", uk: "вечеря", ru: "ужин" },
  { id: 281, word: "collation", uk: "перекус", ru: "перекус" },
  { id: 282, word: "nourriture", uk: "їжа", ru: "еда" },
  { id: 283, word: "boisson", uk: "напій", ru: "напиток" },
  { id: 284, word: "eau", uk: "вода", ru: "вода" },
  { id: 285, word: "jus", uk: "сік", ru: "сок" },
  { id: 286, word: "thé", uk: "чай", ru: "чай" },
  { id: 287, word: "café", uk: "кава", ru: "кофе" },
  { id: 288, word: "lait", uk: "молоко", ru: "молоко" },
  { id: 289, word: "pain", uk: "хліб", ru: "хлеб" },
  { id: 290, word: "beurre", uk: "масло", ru: "масло" },
  { id: 291, word: "fromage", uk: "сир", ru: "сыр" },
  { id: 292, word: "oeuf", uk: "яйце", ru: "яйцо" },
  { id: 293, word: "riz", uk: "рис", ru: "рис" },
  { id: 294, word: "pâtes", uk: "паста/макарони", ru: "паста/макароны" },
  { id: 295, word: "soupe", uk: "суп", ru: "суп" },
  { id: 296, word: "salade", uk: "салат", ru: "салат" },
  { id: 297, word: "fruit", uk: "фрукти", ru: "фрукты" },
  { id: 298, word: "pomme", uk: "яблуко", ru: "яблоко" },
  { id: 299, word: "banane", uk: "банан", ru: "банан" },
  { id: 300, word: "orange", uk: "апельсин", ru: "апельсин" },
  { id: 301, word: "citron", uk: "лимон", ru: "лимон" },
  { id: 302, word: "raisin", uk: "виноград", ru: "виноград" },
  { id: 303, word: "fraise", uk: "полуниця", ru: "клубника" },
  { id: 304, word: "framboise", uk: "малина", ru: "малина" },
  { id: 305, word: "cerise", uk: "вишня", ru: "вишня" },
  { id: 306, word: "pêche", uk: "персик", ru: "персик" },
  { id: 307, word: "poire", uk: "груша", ru: "груша" },
  { id: 308, word: "pastèque", uk: "кавун", ru: "арбуз" },
  { id: 309, word: "melon", uk: "диня", ru: "дыня" },
  { id: 310, word: "légume", uk: "овоч", ru: "овощ" },
  { id: 311, word: "tomate", uk: "помідор", ru: "помидор" },
  { id: 312, word: "concombre", uk: "огірок", ru: "огурец" },
  { id: 313, word: "carotte", uk: "морква", ru: "морковь" },
  { id: 314, word: "pomme de terre", uk: "картопля", ru: "картофель" },
  { id: 315, word: "chou", uk: "капуста", ru: "капуста" },
  { id: 316, word: "laitue", uk: "салат (листя)", ru: "салат" },
  { id: 317, word: "champignon", uk: "гриб", ru: "гриб" },
  { id: 318, word: "viande", uk: "м’ясо", ru: "мясо" },
  { id: 319, word: "boeuf", uk: "яловичина", ru: "говядина" },
  { id: 320, word: "porc", uk: "свинина", ru: "свинина" },
  { id: 321, word: "poulet", uk: "курятина", ru: "курятина" },
  { id: 322, word: "dinde", uk: "індичка", ru: "индейка" },
  { id: 323, word: "poisson", uk: "риба", ru: "рыба" },
  { id: 324, word: "saucisse", uk: "ковбаса", ru: "колбаса" },
  { id: 325, word: "jambon", uk: "шинка", ru: "ветчина" },
  { id: 326, word: "sauce", uk: "соус", ru: "соус" },
  { id: 327, word: "sel", uk: "сіль", ru: "соль" },
  { id: 328, word: "sucre", uk: "цукор", ru: "сахар" },
  { id: 329, word: "poivre", uk: "перець", ru: "перец" },
  { id: 330, word: "huile", uk: "олія", ru: "масло (раст.)" },
  { id: 331, word: "vinaigre", uk: "оцет", ru: "уксус" },
  { id: 332, word: "crème", uk: "вершки/крем", ru: "сливки/крем" },
  { id: 333, word: "yaourt", uk: "йогурт", ru: "йогурт" },
  { id: 334, word: "glace", uk: "морозиво", ru: "мороженое" },
  { id: 335, word: "gâteau", uk: "торт/тістечко", ru: "торт/пирожное" },
  { id: 336, word: "tarte", uk: "пиріг", ru: "пирог" },
  { id: 337, word: "biscuit", uk: "печиво", ru: "печенье" },
  { id: 338, word: "petit pain", uk: "булочка", ru: "булочка" },
  { id: 339, word: "kéfir", uk: "кефір", ru: "кефир" },
  { id: 340, word: "crème fraîche", uk: "сметана", ru: "сметана" }
];

window.decks.fr_adverbs = [
  { id: 1, word: "maintenant", uk: "зараз", ru: "сейчас" },
  { id: 2, word: "déjà", uk: "вже", ru: "уже" },
  { id: 3, word: "encore", uk: "ще/знову", ru: "ещё/снова" },
  { id: 4, word: "seulement", uk: "тільки", ru: "только" },
  { id: 5, word: "aussi", uk: "також", ru: "тоже" },
  { id: 6, word: "très", uk: "дуже", ru: "очень" },
  { id: 7, word: "toujours", uk: "завжди", ru: "всегда" },
  { id: 8, word: "jamais", uk: "ніколи", ru: "никогда" },
  { id: 9, word: "parfois", uk: "іноді", ru: "иногда" },
  { id: 10, word: "souvent", uk: "часто", ru: "часто" },
  { id: 11, word: "rarement", uk: "рідко", ru: "редко" },
  { id: 12, word: "bientôt", uk: "незабаром", ru: "скоро" },
  { id: 13, word: "tout de suite", uk: "відразу", ru: "сразу" },
  { id: 14, word: "aujourd’hui", uk: "сьогодні", ru: "сегодня" },
  { id: 15, word: "hier", uk: "вчора", ru: "вчера" },
  { id: 16, word: "demain", uk: "завтра", ru: "завтра" },
  { id: 17, word: "plus tard", uk: "пізніше", ru: "позже" },
  { id: 18, word: "puis", uk: "потім", ru: "затем" },
  { id: 19, word: "soudain", uk: "раптом", ru: "вдруг" },
  { id: 20, word: "enfin", uk: "нарешті", ru: "наконец" }
];

window.decks.fr_adjectives = [
  { id: 1, word: "bon/bonne", uk: "добрий", ru: "хороший" },
  { id: 2, word: "mauvais/mauvaise", uk: "поганий", ru: "плохой" },
  { id: 3, word: "grand/grande", uk: "великий", ru: "большой" },
  { id: 4, word: "petit/petite", uk: "малий", ru: "маленький" },
  { id: 5, word: "beau/belle", uk: "гарний", ru: "красивый" },
  { id: 6, word: "moche", uk: "потворний", ru: "уродливый" },
  { id: 7, word: "nouveau/nouvelle", uk: "новий", ru: "новый" },
  { id: 8, word: "vieux/vieille", uk: "старий", ru: "старый" },
  { id: 9, word: "jeune", uk: "молодий", ru: "молодой" },
  { id: 10, word: "facile", uk: "легкий/простий", ru: "лёгкий/простой" },
  { id: 11, word: "difficile", uk: "складний", ru: "сложный" },
  { id: 12, word: "rapide", uk: "швидкий", ru: "быстрый" },
  { id: 13, word: "lent/lente", uk: "повільний", ru: "медленный" },
  { id: 14, word: "chaud/chaude", uk: "гарячий", ru: "горячий" },
  { id: 15, word: "froid/froide", uk: "холодний", ru: "холодный" },
  { id: 16, word: "amical/amicale", uk: "дружній", ru: "дружелюбный" },
  { id: 17, word: "sympa", uk: "приємний", ru: "милый" },
  { id: 18, word: "méchant/méchante", uk: "злий/підлий", ru: "злой/подлый" },
  { id: 19, word: "drôle", uk: "смішний", ru: "весёлый" },
  { id: 20, word: "triste", uk: "сумний", ru: "грустный" },
  { id: 21, word: "calme", uk: "спокійний", ru: "спокойный" }
];

window.decks.fr_prepositions = [
  { id: 1, word: "à", uk: "до/у/в", ru: "к/в" },
  { id: 2, word: "de", uk: "з/від/род.", ru: "из/от/род." },
  { id: 3, word: "dans", uk: "в (усередині)", ru: "в (внутри)" },
  { id: 4, word: "en", uk: "в/у", ru: "в/на" },
  { id: 5, word: "sur", uk: "на", ru: "на" },
  { id: 6, word: "sous", uk: "під", ru: "под" },
  { id: 7, word: "chez", uk: "у (в когось)", ru: "у (у кого-то)" },
  { id: 8, word: "avec", uk: "з", ru: "с" },
  { id: 9, word: "sans", uk: "без", ru: "без" },
  { id: 10, word: "pour", uk: "для/щоб", ru: "для/чтобы" },
  { id: 11, word: "par", uk: "через/кимось", ru: "через/кем-либо" },
  { id: 12, word: "contre", uk: "проти", ru: "против" },
  { id: 13, word: "entre", uk: "між", ru: "между" },
  { id: 14, word: "parmi", uk: "серед", ru: "среди" },
  { id: 15, word: "vers", uk: "до/у бік", ru: "к" },
  { id: 16, word: "avant", uk: "до (час)", ru: "до" },
  { id: 17, word: "après", uk: "після", ru: "после" },
  { id: 18, word: "pendant", uk: "під час", ru: "во время" },
  { id: 19, word: "depuis", uk: "з/від (час)", ru: "с (о времени)" },
  { id: 20, word: "jusqu’à", uk: "до (місця/часу)", ru: "до" },
  { id: 21, word: "autour de", uk: "навколо", ru: "вокруг" }
];

window.decks.fr_pronouns = [
  { id: 1, word: "je", uk: "я", ru: "я" },
  { id: 2, word: "tu", uk: "ти", ru: "ты" },
  { id: 3, word: "il", uk: "він", ru: "он" },
  { id: 4, word: "elle", uk: "вона", ru: "она" },
  { id: 5, word: "on", uk: "ми/хтось", ru: "мы/кто-то" },
  { id: 6, word: "nous", uk: "ми", ru: "мы" },
  { id: 7, word: "vous", uk: "ви", ru: "вы" },
  { id: 8, word: "ils", uk: "вони (чол.)", ru: "они (м.)" },
  { id: 9, word: "elles", uk: "вони (жін.)", ru: "они (ж.)" },
  { id: 10, word: "me", uk: "мене", ru: "меня" },
  { id: 11, word: "te", uk: "тебе", ru: "тебя" },
  { id: 12, word: "le", uk: "його (прям.)", ru: "его (прям.)" },
  { id: 13, word: "la", uk: "її (прям.)", ru: "её (прям.)" },
  { id: 14, word: "lui", uk: "йому", ru: "ему" },
  { id: 15, word: "leur", uk: "їм", ru: "им" },
  { id: 16, word: "moi", uk: "я (ударн.)", ru: "я (ударн.)" },
  { id: 17, word: "toi", uk: "ти (ударн.)", ru: "ты (ударн.)" },
  { id: 18, word: "mon", uk: "мій", ru: "мой" },
  { id: 19, word: "ton", uk: "твій", ru: "твой" },
  { id: 20, word: "son", uk: "його/її", ru: "его/её" },
  { id: 21, word: "notre", uk: "наш", ru: "наш" },
  { id: 22, word: "votre", uk: "ваш", ru: "ваш" },
  { id: 23, word: "leur (poss.)", uk: "їхній", ru: "их" },
  { id: 24, word: "ceci", uk: "це", ru: "это" },
  { id: 25, word: "cela/ça", uk: "те/це", ru: "то/это" }
];

window.decks.fr_numbers = [
  { id: 1, word: "un", uk: "один", ru: "один" },
  { id: 2, word: "deux", uk: "два", ru: "два" },
  { id: 3, word: "trois", uk: "три", ru: "три" },
  { id: 4, word: "quatre", uk: "чотири", ru: "четыре" },
  { id: 5, word: "cinq", uk: "п’ять", ru: "пять" },
  { id: 6, word: "six", uk: "шість", ru: "шесть" },
  { id: 7, word: "sept", uk: "сім", ru: "семь" },
  { id: 8, word: "huit", uk: "вісім", ru: "восемь" },
  { id: 9, word: "neuf", uk: "дев’ять", ru: "девять" },
  { id: 10, word: "dix", uk: "десять", ru: "десять" },
  { id: 11, word: "onze", uk: "одинадцять", ru: "одиннадцать" },
  { id: 12, word: "douze", uk: "дванадцять", ru: "двенадцать" },
  { id: 13, word: "treize", uk: "тринадцять", ru: "тринадцать" },
  { id: 14, word: "quatorze", uk: "чотирнадцять", ru: "четырнадцать" },
  { id: 15, word: "quinze", uk: "п’ятнадцять", ru: "пятнадцать" },
  { id: 16, word: "seize", uk: "шістнадцять", ru: "шестнадцать" },
  { id: 17, word: "vingt", uk: "двадцять", ru: "двадцать" },
  { id: 18, word: "trente", uk: "тридцять", ru: "тридцать" },
  { id: 19, word: "quarante", uk: "сорок", ru: "сорок" },
  { id: 20, word: "cinquante", uk: "п’ятдесят", ru: "пятьдесят" },
  { id: 21, word: "soixante", uk: "шістдесят", ru: "шестьдесят" },
  { id: 22, word: "soixante-dix", uk: "сімдесят", ru: "семьдесят" },
  { id: 23, word: "quatre-vingts", uk: "вісімдесят", ru: "восемьдесят" },
  { id: 24, word: "quatre-vingt-dix", uk: "дев’яносто", ru: "девяносто" },
  { id: 25, word: "cent", uk: "сто", ru: "сто" },
  { id: 26, word: "mille", uk: "тисяча", ru: "тысяча" }
];

window.decks.fr_conjunctions = [
  { id: 1, word: "et", uk: "і", ru: "и" },
  { id: 2, word: "ou", uk: "або", ru: "или" },
  { id: 3, word: "mais", uk: "але", ru: "но" },
  { id: 4, word: "car", uk: "бо", ru: "ибо" },
  { id: 5, word: "parce que", uk: "тому що", ru: "потому что" },
  { id: 6, word: "que", uk: "що", ru: "что" },
  { id: 7, word: "si", uk: "якщо", ru: "если" },
  { id: 8, word: "bien que", uk: "хоча", ru: "хотя" },
  { id: 9, word: "tandis que", uk: "тоді як", ru: "тогда как" },
  { id: 10, word: "avant que", uk: "перш ніж", ru: "прежде чем" },
  { id: 11, word: "après que", uk: "після того як", ru: "после того как" },
  { id: 12, word: "dès que", uk: "як тільки", ru: "как только" },
  { id: 13, word: "afin que", uk: "щоб", ru: "чтобы" },
  { id: 14, word: "donc", uk: "отже/значить", ru: "значит" },
  { id: 15, word: "alors", uk: "тоді/отже", ru: "тогда/итак" },
  { id: 16, word: "cependant", uk: "однак", ru: "однако" },
  { id: 17, word: "puisque", uk: "оскільки", ru: "поскольку" }
];

/* ====================== End of file =======================
 * File: deck.fr.js • Version: 1.0 • 2025-10-19
*/
